import type { TaskCategory } from './types';

// Aufgaben-Regeln (siehe tasks.test.ts):
// - kurze Nenn-Aufgabe, in einer Sekunde erfassbar
// - jeder am Tisch kann OHNE Spezialwissen antworten
// - viele mögliche Antworten pro Aufgabe (die Bombe geht mehrfach rum)
export const taskCategoriesDe: TaskCategory[] = [
  {
    id: 'klassik',
    name: 'Klassiker',
    icon: '🎲',
    image: 'easy',
    tasks: [
      'Nenne eine Automarke',
      'Nenne eine Farbe',
      'Nenne ein Land in Europa',
      'Nenne eine Hauptstadt',
      'Nenne eine Obstsorte',
      'Nenne ein Gemüse',
      'Nenne ein Tier im Zoo',
      'Nenne ein Haustier',
      'Nenne einen Jungennamen',
      'Nenne einen Mädchennamen',
      'Nenne einen Beruf',
      'Nenne ein Möbelstück',
      'Nenne ein Kleidungsstück',
      'Nenne eine Sprache',
      'Nenne ein Schulfach',
      'Nenne ein Musikinstrument',
      'Nenne eine deutsche Stadt',
      'Nenne einen Fluss',
      'Nenne ein Körperteil',
      'Nenne etwas, das fliegt',
      'Nenne etwas, das schwimmt',
      'Nenne etwas aus der Küche',
      'Nenne etwas, das rund ist',
      'Nenne etwas, das kalt ist',
      'Nenne etwas, das heiß ist',
      'Nenne ein Werkzeug',
      'Nenne eine Blume',
      'Nenne einen Baum',
      'Nenne ein Insekt',
      'Nenne einen Vogel',
      'Nenne etwas, das leuchtet',
      'Nenne ein Fahrzeug',
      'Nenne einen Monat',
      'Nenne ein Wetterphänomen',
      'Nenne etwas aus dem Badezimmer',
      'Nenne etwas, das laut ist',
    ],
  },
  {
    id: 'food',
    name: 'Essen & Trinken',
    icon: '🍕',
    tasks: [
      'Nenne einen Pizzabelag',
      'Nenne eine Eissorte',
      'Nenne ein Fastfood-Gericht',
      'Nenne eine Nudelsorte',
      'Nenne einen Käse',
      'Nenne ein Getränk ohne Alkohol',
      'Nenne einen Cocktail',
      'Nenne eine Biermarke',
      'Nenne eine Süßigkeit',
      'Nenne eine Schokoladenmarke',
      'Nenne ein Gericht mit Kartoffeln',
      'Nenne ein Gericht mit Reis',
      'Nenne etwas vom Bäcker',
      'Nenne einen Brotaufstrich',
      'Nenne ein Gewürz',
      'Nenne eine Teesorte',
      'Nenne etwas vom Frühstückstisch',
      'Nenne ein Gericht aus Italien',
      'Nenne ein Gericht aus Asien',
      'Nenne einen Salat',
      'Nenne eine Suppe',
      'Nenne einen Nachtisch',
      'Nenne eine Beere',
      'Nenne eine Nusssorte',
      'Nenne etwas, das man grillt',
      'Nenne einen Saft',
      'Nenne eine Limonadenmarke',
      'Nenne etwas aus der Tiefkühltruhe',
      'Nenne ein Milchprodukt',
      'Nenne etwas, das sauer schmeckt',
      'Nenne etwas, das man roh isst',
      'Nenne ein Kantinengericht',
      'Nenne einen Döner-Zutat',
      'Nenne eine Kuchensorte',
      'Nenne etwas, das man dippen kann',
      'Nenne ein Gericht deiner Kindheit',
    ],
  },
  {
    id: 'pop',
    name: 'Promis & Popkultur',
    icon: '🌟',
    image: 'stars',
    tasks: [
      'Nenne einen Fußballer',
      'Nenne eine Sängerin',
      'Nenne einen Rapper',
      'Nenne eine Band',
      'Nenne einen Disney-Film',
      'Nenne eine Netflix-Serie',
      'Nenne einen Superhelden',
      'Nenne einen Bösewicht aus einem Film',
      'Nenne einen Schauspieler',
      'Nenne eine Schauspielerin',
      'Nenne einen YouTuber oder Streamer',
      'Nenne einen deutschen Promi',
      'Nenne einen Song, den alle kennen',
      'Nenne ein Videospiel',
      'Nenne eine Zeichentrickfigur',
      'Nenne einen Film mit Tieren',
      'Nenne eine Boyband',
      'Nenne einen James-Bond-Darsteller oder -Film',
      'Nenne eine Talkshow oder Castingshow',
      'Nenne einen Harry-Potter-Charakter',
      'Nenne einen Star-Wars-Charakter',
      'Nenne eine App auf deinem Handy',
      'Nenne einen Horrorfilm',
      'Nenne einen Weihnachtsfilm',
      'Nenne einen Animationsfilm',
      'Nenne eine berühmte Familie',
      'Nenne einen Sportler, der kein Fußballer ist',
      'Nenne eine Sportart bei Olympia',
      'Nenne einen Milliardär',
      'Nenne eine Marvel-Figur',
      'Nenne einen Simpsons-Charakter',
      'Nenne einen Song zum Mitgrölen',
      'Nenne eine Serie, die abgesetzt wurde',
      'Nenne einen Kinderbuch-Helden',
      'Nenne einen Präsidenten oder Kanzler',
      'Nenne eine berühmte Blondine',
    ],
  },
  {
    id: 'ortereisen',
    name: 'Orte & Reisen',
    icon: '🌍',
    image: 'countries',
    tasks: [
      'Nenne ein Urlaubsland',
      'Nenne eine Insel',
      'Nenne eine Stadt mit Strand',
      'Nenne ein Land in Asien',
      'Nenne ein Land in Afrika',
      'Nenne ein Land, in dem es heiß ist',
      'Nenne ein Land, in dem es kalt ist',
      'Nenne eine europäische Hauptstadt',
      'Nenne eine Airline',
      'Nenne etwas, das man in den Koffer packt',
      'Nenne etwas am Flughafen',
      'Nenne ein Gebirge',
      'Nenne einen See oder ein Meer',
      'Nenne eine Sehenswürdigkeit',
      'Nenne ein Bundesland',
      'Nenne eine Stadt in Bayern',
      'Nenne eine Millionenstadt',
      'Nenne ein Land mit rotem Element in der Flagge',
      'Nenne eine Währung',
      'Nenne etwas, das man am Strand macht',
      'Nenne etwas, das man beim Camping braucht',
      'Nenne eine Stadt mit U-Bahn',
      'Nenne ein Reiseziel für Backpacker',
      'Nenne ein Land, dessen Sprache du nicht sprichst',
      'Nenne etwas, das man im Hotel findet',
      'Nenne eine Stadt, in der du noch nie warst',
      'Nenne ein Nachbarland von Deutschland',
      'Nenne eine Skiregion oder einen Wintersportort',
      'Nenne etwas, das man auf einer Autofahrt macht',
      'Nenne eine berühmte Straße oder einen Platz',
      'Nenne ein Land mit gutem Essen',
      'Nenne einen Ort, an dem man leise sein muss',
      'Nenne etwas, das man im Zug macht',
      'Nenne eine Stadt mit berühmtem Fußballverein',
      'Nenne ein Ziel für eine Klassenfahrt',
      'Nenne ein Land, in das du auswandern würdest',
    ],
  },
  {
    id: 'buchstaben',
    name: 'Buchstaben-Chaos',
    icon: '🔤',
    image: 'buchstaben',
    tasks: [
      'Nenne ein Tier mit A',
      'Nenne ein Tier mit K',
      'Nenne ein Tier mit S',
      'Nenne eine Stadt mit B',
      'Nenne eine Stadt mit M',
      'Nenne ein Land mit I',
      'Nenne ein Land mit S',
      'Nenne einen Namen mit L',
      'Nenne einen Namen mit T',
      'Nenne ein Essen mit P',
      'Nenne ein Essen mit K',
      'Nenne einen Beruf mit F',
      'Nenne einen Beruf mit M',
      'Nenne ein Wort mit mehr als drei Silben',
      'Nenne ein Wort, das mit Z anfängt',
      'Nenne ein Wort, das auf -ung endet',
      'Nenne ein Wort, das auf -heit endet',
      'Nenne ein zusammengesetztes Wort mit Haus',
      'Nenne ein zusammengesetztes Wort mit Bier',
      'Nenne ein Wort mit Doppel-S',
      'Nenne eine Farbe, die nicht im Regenbogen ist',
      'Nenne ein Tier, das mit demselben Buchstaben wie dein Name beginnt',
      'Nenne eine Marke mit A',
      'Nenne eine Marke mit N',
      'Nenne einen Fluss mit R',
      'Nenne ein Getränk mit C',
      'Nenne einen Gegenstand im Raum mit T',
      'Nenne einen Gegenstand im Raum mit S',
      'Nenne ein Körperteil mit H',
      'Nenne einen Promi mit D',
      'Nenne einen Promi mit J',
      'Nenne einen Film mit T',
      'Nenne ein Auto-Modell mit G',
      'Nenne ein englisches Wort mit W',
      'Nenne ein Schimpfwort, das jugendfrei ist',
      'Nenne ein Wort, das rückwärts gelesen auch ein Wort ist',
    ],
  },
  {
    id: 'partyfun',
    name: 'Party & Peinlich',
    icon: '🎉',
    image: 'party',
    tasks: [
      'Nenne eine Ausrede fürs Zuspätkommen',
      'Nenne etwas, das man auf einer Party nicht tun sollte',
      'Nenne einen schlechten Anmachspruch',
      'Nenne etwas, das im Kühlschrank einer WG steht',
      'Nenne einen Grund, warum man einen Kater hat',
      'Nenne ein Trinkspiel',
      'Nenne einen Song für die Tanzfläche',
      'Nenne etwas Peinliches, das im Urlaub passieren kann',
      'Nenne einen Grund, jemanden zu ghosten',
      'Nenne eine schlechte Karaoke-Songwahl',
      'Nenne etwas, das man morgens nach der Party bereut',
      'Nenne ein schlechtes Geburtstagsgeschenk',
      'Nenne etwas, das man heimlich googelt',
      'Nenne eine Lüge im Lebenslauf',
      'Nenne etwas, das Eltern peinlich finden',
      'Nenne eine Ausrede, um früher zu gehen',
      'Nenne etwas, das man im Club verliert',
      'Nenne einen Grund für einen Streit im Urlaub',
      'Nenne etwas, das man nicht laut sagen sollte',
      'Nenne ein Thema, das man beim ersten Date meidet',
      'Nenne etwas, das nach Mitternacht bestellt wird',
      'Nenne einen Tanzmove, den alle können',
      'Nenne etwas, das in jeder WhatsApp-Gruppe passiert',
      'Nenne einen Grund, warum das WLAN schuld ist',
      'Nenne etwas, das man beim Umzug nie wiederfindet',
      'Nenne eine Sache, die Betrunkene gerne kaufen',
      'Nenne etwas, das man an Silvester bereut',
      'Nenne einen Spitznamen für einen Freund',
      'Nenne etwas, das auf Festival-Toiletten passiert',
      'Nenne einen Grund, das Handy stumm zu schalten',
      'Nenne etwas, das man beim Flunkyball falsch machen kann',
      'Nenne eine Regel, die jede Party braucht',
      'Nenne etwas, das man um 4 Uhr morgens isst',
      'Nenne einen Ort für einen peinlichen Sturz',
      'Nenne etwas, das der Türsteher nicht sehen darf',
      'Nenne einen Grund, warum der Abend eskaliert ist',
    ],
  },
  {
    id: 'pikant',
    name: '18+ Pikant',
    icon: '🔞',
    image: 'adult',
    adult: true,
    tasks: [
      'Nenne einen Ort für ein heimliches Date',
      'Nenne etwas, das man beim Flirten falsch machen kann',
      'Nenne eine Dating-App',
      'Nenne einen Kosenamen für den Partner',
      'Nenne etwas, das in einem Liebesfilm nie fehlt',
      'Nenne einen Grund für einen Seitensprung-Verdacht',
      'Nenne etwas, das man beim ersten Kuss falsch machen kann',
      'Nenne einen unpassenden Ort zum Knutschen',
      'Nenne etwas, das man auf dem Nachttisch findet',
      'Nenne einen Promi, mit dem du ein Date wollen würdest',
      'Nenne eine schlechte erste Nachricht beim Online-Dating',
      'Nenne etwas, das an einem Junggesellenabschied passiert',
      'Nenne einen Grund, warum ein Date früher endet',
      'Nenne etwas Verführerisches zum Anziehen',
      'Nenne einen Song für ein romantisches Dinner',
      'Nenne etwas, das man vor dem Date checkt',
      'Nenne eine Ausrede, wenn man erwischt wird',
      'Nenne etwas, das in einem Hotelzimmer versteckt wird',
      'Nenne einen peinlichen Moment beim Kennenlernen',
      'Nenne etwas, das man dem Ex nicht schreiben sollte',
      'Nenne einen Ort, an dem schon geflirtet wurde, wo es verboten ist',
      'Nenne ein Körperteil, das man schön finden kann',
      'Nenne etwas, das die Stimmung killt',
      'Nenne einen Film mit einer berühmten Kuss-Szene',
      'Nenne etwas, das man beim Blind Date sofort bemerkt',
      'Nenne einen Grund, die Handynummer nicht zu geben',
      'Nenne etwas, das auf der Reeperbahn passiert',
      'Nenne einen Vorteil einer Fernbeziehung',
      'Nenne etwas, das man im Sommer am Strand beobachtet',
      'Nenne eine Frage, die man beim ersten Date nicht stellt',
      'Nenne etwas, das nach dem ersten Date überanalysiert wird',
      'Nenne einen Ort für einen Heiratsantrag',
      'Nenne etwas, das in Romantikkomödien immer passiert',
      'Nenne ein Kompliment, das nach hinten losgeht',
      'Nenne etwas, das man aus der Wohnung räumt, bevor Besuch kommt',
      'Nenne einen Grund, warum das Licht ausbleibt',
    ],
  },
];
