import type { Category } from './types';

// Hint-Regeln (siehe words.test.ts) — kalibriert an echten Spielrunden:
// - genau ein Wort pro Hint
// - EIN Assoziationsschritt, den fast jeder von selbst geht
// - kein definierender Bestandteil des Worts (zu nah: Tennis -> Filzball)
// - kein Fachwissen, keine private Verknüpfung (zu weit: Nike -> Siegesgöttin)
// - kein Kategorie-Etikett (Obst, Tier, Gerät, Hauptstadt)
// - lieber ein markantes Bild als ein blasser Oberbegriff
export const categoriesDe: Category[] = [
  {
    id: 'easy',
    name: 'Einfache Wörter',
    icon: '🎲',
    hint: 'Alltag',
    words: [
      { word: 'Apfel', hint: 'Schneewittchen' }, { word: 'Hund', hint: 'Knochen' }, { word: 'Sonne', hint: 'Schatten' }, { word: 'Buch', hint: 'Lesezeichen' }, { word: 'Stuhl', hint: 'Tisch' },
      { word: 'Wasser', hint: 'Durst' }, { word: 'Fenster', hint: 'Aussicht' }, { word: 'Schuh', hint: 'Barfuß' }, { word: 'Baum', hint: 'Klettern' }, { word: 'Auto', hint: 'Stau' },
      { word: 'Tasse', hint: 'Tee' }, { word: 'Brille', hint: 'Verschwommen' }, { word: 'Schlüssel', hint: 'Verloren' }, { word: 'Uhr', hint: 'Ticken' }, { word: 'Kissen', hint: 'Schlacht' },
      { word: 'Löffel', hint: 'Suppe' }, { word: 'Regen', hint: 'Pfütze' }, { word: 'Berg', hint: 'Lawine' }, { word: 'Brücke', hint: 'Fluss' }, { word: 'Kerze', hint: 'Pusten' },
      { word: 'Spiegel', hint: 'Eitelkeit' }, { word: 'Teppich', hint: 'Fleck' }, { word: 'Zahnbürste', hint: 'Karies' }, { word: 'Regenschirm', hint: 'Windböe' }, { word: 'Bleistift', hint: 'Skizze' },
      { word: 'Ballon', hint: 'Schweben' }, { word: 'Koffer', hint: 'Gepäckband' }, { word: 'Handschuh', hint: 'Frieren' }, { word: 'Wecker', hint: 'Verschlafen' }, { word: 'Gabel', hint: 'Piksen' },
      { word: 'Seife', hint: 'Rutschig' }, { word: 'Lampe', hint: 'Motten' }, { word: 'Fahrrad', hint: 'Helm' }, { word: 'Wolke', hint: 'Schäfchen' }, { word: 'Blume', hint: 'Vase' },
      { word: 'Feuer', hint: 'Rauch' }, { word: 'Leiter', hint: 'Wackelig' }, { word: 'Zelt', hint: 'Schlafsack' }, { word: 'Kamm', hint: 'Scheitel' }, { word: 'Knopf', hint: 'Annähen' },
      { word: 'Seil', hint: 'Ziehen' }, { word: 'Kalender', hint: 'Termin' }, { word: 'Briefmarke', hint: 'Lecken' }, { word: 'Mütze', hint: 'Winter' }, { word: 'Socke', hint: 'Löcher' },
      { word: 'Nagel', hint: 'Wand' }, { word: 'Taschenlampe', hint: 'Keller' }, { word: 'Zeitung', hint: 'Schlagzeile' }, { word: 'Geschenk', hint: 'Auspacken' }, { word: 'Streichholz', hint: 'Schachtel' }
    ],
  },
  {
    id: 'food',
    name: 'Essen & Trinken',
    icon: '🍕',
    hint: 'Essen',
    words: [
      { word: 'Pizza', hint: 'Lieferdienst' }, { word: 'Spaghetti', hint: 'Kleckern' }, { word: 'Sushi', hint: 'Stäbchen' }, { word: 'Burger', hint: 'Fastfood' }, { word: 'Schokolade', hint: 'Nervennahrung' },
      { word: 'Käse', hint: 'Maus' }, { word: 'Banane', hint: 'Affe' }, { word: 'Kaffee', hint: 'Wachmacher' }, { word: 'Eis', hint: 'Schmelzen' }, { word: 'Suppe', hint: 'Erkältung' },
      { word: 'Salat', hint: 'Beilage' }, { word: 'Pommes', hint: 'Mayo' }, { word: 'Pfannkuchen', hint: 'Wenden' }, { word: 'Brezel', hint: 'Knoten' }, { word: 'Döner', hint: 'Spieß' },
      { word: 'Currywurst', hint: 'Imbissbude' }, { word: 'Popcorn', hint: 'Kinosaal' }, { word: 'Honig', hint: 'Bär' }, { word: 'Erdbeere', hint: 'Sahne' }, { word: 'Zitrone', hint: 'Presse' },
      { word: 'Reis', hint: 'Klebrig' }, { word: 'Nudeln', hint: 'Sieb' }, { word: 'Toast', hint: 'Angebrannt' }, { word: 'Croissant', hint: 'Halbmond' }, { word: 'Waffel', hint: 'Puderzucker' },
      { word: 'Muffin', hint: 'Förmchen' }, { word: 'Steak', hint: 'Blutig' }, { word: 'Lachs', hint: 'Räuchern' }, { word: 'Kürbis', hint: 'Halloween' }, { word: 'Gurke', hint: 'Maske' },
      { word: 'Wassermelone', hint: 'Kerne' }, { word: 'Ananas', hint: 'Dose' }, { word: 'Bier', hint: 'Schaumkrone' }, { word: 'Ketchup', hint: 'Flaschenhals' }, { word: 'Kuchen', hint: 'Kaffeeklatsch' },
      { word: 'Keks', hint: 'Krümel' }, { word: 'Brot', hint: 'Schimmel' }, { word: 'Ei', hint: 'Pfanne' }, { word: 'Butter', hint: 'Streichen' }, { word: 'Marmelade', hint: 'Einkochen' },
      { word: 'Joghurt', hint: 'Becher' }, { word: 'Müsli', hint: 'Schüssel' }, { word: 'Pesto', hint: 'Mörser' }, { word: 'Tacos', hint: 'Mexiko' }, { word: 'Ramen', hint: 'Schlürfen' },
      { word: 'Falafel', hint: 'Bällchen' }, { word: 'Tiramisu', hint: 'Nachtisch' }, { word: 'Gulasch', hint: 'Ungarn' }, { word: 'Schnitzel', hint: 'Klopfen' }, { word: 'Knoblauch', hint: 'Atem' }
    ],
  },
  {
    id: 'animals',
    name: 'Tiere',
    icon: '🐾',
    hint: 'Tier',
    words: [
      { word: 'Elefant', hint: 'Porzellanladen' }, { word: 'Löwe', hint: 'Mut' }, { word: 'Pinguin', hint: 'Frack' }, { word: 'Delfin', hint: 'Klug' }, { word: 'Adler', hint: 'Wappen' },
      { word: 'Krokodil', hint: 'Tränen' }, { word: 'Giraffe', hint: 'Baumkrone' }, { word: 'Känguru', hint: 'Boxen' }, { word: 'Igel', hint: 'Zusammenrollen' }, { word: 'Fuchs', hint: 'Schlau' },
      { word: 'Wolf', hint: 'Vollmond' }, { word: 'Bär', hint: 'Winterschlaf' }, { word: 'Hai', hint: 'Filmmusik' }, { word: 'Oktopus', hint: 'Tintenwolke' }, { word: 'Papagei', hint: 'Nachplappern' },
      { word: 'Schildkröte', hint: 'Uralt' }, { word: 'Frosch', hint: 'Prinz' }, { word: 'Schlange', hint: 'Beschwörer' }, { word: 'Biene', hint: 'Fleißig' }, { word: 'Schmetterling', hint: 'Verwandlung' },
      { word: 'Eule', hint: 'Weisheit' }, { word: 'Zebra', hint: 'Fußgängerüberweg' }, { word: 'Nashorn', hint: 'Wilderer' }, { word: 'Flamingo', hint: 'Einbeinig' }, { word: 'Waschbär', hint: 'Mülltonne' },
      { word: 'Faultier', hint: 'Zeitlupe' }, { word: 'Panda', hint: 'Artenschutz' }, { word: 'Koala', hint: 'Australien' }, { word: 'Tiger', hint: 'Dschungelbuch' }, { word: 'Affe', hint: 'Nachahmen' },
      { word: 'Kamel', hint: 'Karawane' }, { word: 'Esel', hint: 'Stur' }, { word: 'Kuh', hint: 'Weide' }, { word: 'Pferd', hint: 'Hufeisen' }, { word: 'Maus', hint: 'Piepsen' },
      { word: 'Fledermaus', hint: 'Kopfüber' }, { word: 'Hase', hint: 'Ostern' }, { word: 'Katze', hint: 'Schnurren' }, { word: 'Wal', hint: 'Fontäne' }, { word: 'Robbe', hint: 'Klatschen' },
      { word: 'Pfau', hint: 'Eitel' }, { word: 'Strauß', hint: 'Flugunfähig' }, { word: 'Hamster', hint: 'Laufrad' }, { word: 'Chamäleon', hint: 'Tarnung' }, { word: 'Skorpion', hint: 'Sternzeichen' },
      { word: 'Qualle', hint: 'Durchsichtig' }, { word: 'Ameise', hint: 'Staat' }, { word: 'Libelle', hint: 'Schillern' }, { word: 'Seepferdchen', hint: 'Aufrecht' }, { word: 'Murmeltier', hint: 'Pfiff' }
    ],
  },
  {
    id: 'places',
    name: 'Orte',
    icon: '📍',
    hint: 'Ort',
    words: [
      { word: 'Strand', hint: 'Sonnencreme' }, { word: 'Flughafen', hint: 'Abflugtafel' }, { word: 'Krankenhaus', hint: 'Besuchszeit' }, { word: 'Schule', hint: 'Pausenklingel' }, { word: 'Kino', hint: 'Dunkel' },
      { word: 'Bahnhof', hint: 'Durchsage' }, { word: 'Supermarkt', hint: 'Kasse' }, { word: 'Bibliothek', hint: 'Lesesaal' }, { word: 'Zoo', hint: 'Gitter' }, { word: 'Museum', hint: 'Anfassen' },
      { word: 'Park', hint: 'Spaziergang' }, { word: 'Restaurant', hint: 'Trinkgeld' }, { word: 'Schwimmbad', hint: 'Chlor' }, { word: 'Fitnessstudio', hint: 'Vorsatz' }, { word: 'Kirche', hint: 'Orgel' },
      { word: 'Schloss', hint: 'Ritter' }, { word: 'Wüste', hint: 'Fata' }, { word: 'Dschungel', hint: 'Machete' }, { word: 'Vulkan', hint: 'Asche' }, { word: 'Insel', hint: 'Schiffbruch' },
      { word: 'Höhle', hint: 'Echo' }, { word: 'Leuchtturm', hint: 'Nebel' }, { word: 'Hafen', hint: 'Container' }, { word: 'Stadion', hint: 'Sprechchor' }, { word: 'Zirkus', hint: 'Zelt' },
      { word: 'Bäckerei', hint: 'Frühaufsteher' }, { word: 'Tankstelle', hint: 'Spritpreis' }, { word: 'Bauernhof', hint: 'Misthaufen' }, { word: 'Wald', hint: 'Pilze' }, { word: 'Hotel', hint: 'Zimmerschlüssel' },
      { word: 'Aquarium', hint: 'Scheibe' }, { word: 'Bank', hint: 'Überweisung' }, { word: 'Rathaus', hint: 'Formular' }, { word: 'Gefängnis', hint: 'Freigang' }, { word: 'Friseur', hint: 'Termin' },
      { word: 'Küche', hint: 'Dunstabzug' }, { word: 'Apotheke', hint: 'Beipackzettel' }, { word: 'Spielplatz', hint: 'Sandkasten' }, { word: 'Baustelle', hint: 'Lärm' }, { word: 'Friedhof', hint: 'Stille' },
      { word: 'Jahrmarkt', hint: 'Zuckerwatte' }, { word: 'Sauna', hint: 'Schwitzen' }, { word: 'Casino', hint: 'Jetons' }, { word: 'Theater', hint: 'Vorhang' }, { word: 'Campingplatz', hint: 'Wohnwagen' },
      { word: 'Autobahn', hint: 'Raststätte' }, { word: 'Markt', hint: 'Feilschen' }, { word: 'Moschee', hint: 'Gebetsruf' }, { word: 'Universität', hint: 'Hörsaal' }, { word: 'Polizeiwache', hint: 'Anzeige' }
    ],
  },
  {
    id: 'jobs',
    name: 'Berufe',
    icon: '💼',
    hint: 'Beruf',
    words: [
      { word: 'Arzt', hint: 'Sprechstunde' }, { word: 'Lehrer', hint: 'Rotstift' }, { word: 'Polizist', hint: 'Streife' }, { word: 'Feuerwehrmann', hint: 'Sirene' }, { word: 'Koch', hint: 'Hitze' },
      { word: 'Pilot', hint: 'Turbulenzen' }, { word: 'Bäcker', hint: 'Nachtschicht' }, { word: 'Friseur', hint: 'Trinkgeld' }, { word: 'Anwalt', hint: 'Honorar' }, { word: 'Richter', hint: 'Robe' },
      { word: 'Astronaut', hint: 'Schwerelos' }, { word: 'Bauer', hint: 'Wetterbericht' }, { word: 'Elektriker', hint: 'Sicherung' }, { word: 'Klempner', hint: 'Wasserschaden' }, { word: 'Zahnarzt', hint: 'Angstpatient' },
      { word: 'Krankenpfleger', hint: 'Schichtdienst' }, { word: 'Programmierer', hint: 'Bildschirm' }, { word: 'Ingenieur', hint: 'Konstruktion' }, { word: 'Architekt', hint: 'Entwurf' }, { word: 'Maler', hint: 'Abkleben' },
      { word: 'Musiker', hint: 'Gage' }, { word: 'Schauspieler', hint: 'Textbuch' }, { word: 'Kellner', hint: 'Tablett' }, { word: 'Metzger', hint: 'Theke' }, { word: 'Gärtner', hint: 'Unkraut' },
      { word: 'Mechaniker', hint: 'Ölwechsel' }, { word: 'Fotograf', hint: 'Lächeln' }, { word: 'Journalist', hint: 'Recherche' }, { word: 'Detektiv', hint: 'Beschatten' }, { word: 'Soldat', hint: 'Befehl' },
      { word: 'Fischer', hint: 'Kutter' }, { word: 'Bibliothekar', hint: 'Mahngebühr' }, { word: 'DJ', hint: 'Plattenkoffer' }, { word: 'Tierarzt', hint: 'Impfpass' }, { word: 'Postbote', hint: 'Paketschein' },
      { word: 'Barkeeper', hint: 'Cocktailkarte' }, { word: 'Pfarrer', hint: 'Kanzel' }, { word: 'Schreiner', hint: 'Sägespäne' }, { word: 'Dachdecker', hint: 'Schwindelfrei' }, { word: 'Schornsteinfeger', hint: 'Leiter' },
      { word: 'Taxifahrer', hint: 'Kurzstrecke' }, { word: 'Kapitän', hint: 'Logbuch' }, { word: 'Model', hint: 'Kleidergröße' }, { word: 'Politiker', hint: 'Umfragewerte' }, { word: 'Wissenschaftler', hint: 'Studie' },
      { word: 'Psychologe', hint: 'Zuhören' }, { word: 'Optiker', hint: 'Fassung' }, { word: 'Förster', hint: 'Hochsitz' }, { word: 'Winzer', hint: 'Lese' }, { word: 'Chirurg', hint: 'Operationssaal' }
    ],
  },
  {
    id: 'movies',
    name: 'Filme & Serien',
    icon: '🎬',
    hint: 'Film/Serie',
    words: [
      { word: 'Titanic', hint: 'Schiffshorn' }, { word: 'Avatar', hint: 'Blau' }, { word: 'Batman', hint: 'Fledermaus' }, { word: 'Spider-Man', hint: 'Spinnenbiss' }, { word: 'Harry Potter', hint: 'Internat' },
      { word: 'Star Wars', hint: 'Machtsymbol' }, { word: 'Herr der Ringe', hint: 'Wanderung' }, { word: 'Matrix', hint: 'Simulation' }, { word: 'Frozen', hint: 'Schneemann' }, { word: 'Shrek', hint: 'Sumpf' },
      { word: 'Findet Nemo', hint: 'Vergesslich' }, { word: 'König der Löwen', hint: 'Thronfolge' }, { word: 'Jurassic Park', hint: 'Bernstein' }, { word: 'Fluch der Karibik', hint: 'Kompass' }, { word: 'Fast & Furious', hint: 'Tuning' },
      { word: 'James Bond', hint: 'Martini' }, { word: 'Joker', hint: 'Schminke' }, { word: 'Barbie', hint: 'Pink' }, { word: 'Oppenheimer', hint: 'Wüstentest' }, { word: 'Inception', hint: 'Traumebene' },
      { word: 'Gladiator', hint: 'Arena' }, { word: 'Breaking Bad', hint: 'Chemielehrer' }, { word: 'Game of Thrones', hint: 'Drachen' }, { word: 'Stranger Things', hint: 'Achtziger' }, { word: 'The Office', hint: 'Großraumbüro' },
      { word: 'Friends', hint: 'Sofa' }, { word: 'Haus des Geldes', hint: 'Overall' }, { word: 'Wednesday', hint: 'Zöpfe' }, { word: 'Dark', hint: 'Zeitreise' }, { word: 'Squid Game', hint: 'Kinderspiel' },
      { word: 'Minions', hint: 'Gelb' }, { word: 'Toy Story', hint: 'Cowboy' }, { word: 'Cars', hint: 'Rennstrecke' }, { word: 'Deadpool', hint: 'Antiheld' }, { word: 'Interstellar', hint: 'Wurmloch' },
      { word: 'Avengers', hint: 'Superhelden' }, { word: 'Fight Club', hint: 'Regeln' }, { word: 'Forrest Gump', hint: 'Parkbank' }, { word: 'Der Pate', hint: 'Mafia' }, { word: 'Hangover', hint: 'Vegas' },
      { word: 'E.T.', hint: 'Fahrradkorb' }, { word: 'Ratatouille', hint: 'Sternekoch' }, { word: 'Spongebob', hint: 'Ananas' }, { word: 'Die Simpsons', hint: 'Donuts' }, { word: 'How I Met Your Mother', hint: 'Legendär' },
      { word: 'Prison Break', hint: 'Tattoo' }, { word: 'Sherlock', hint: 'London' }, { word: 'Peaky Blinders', hint: 'Schiebermütze' }, { word: 'Dune', hint: 'Sandwurm' }, { word: 'Zurück in die Zukunft', hint: 'DeLorean' }
    ],
  },
  {
    id: 'stars',
    name: 'Promis',
    icon: '🌟',
    hint: 'Person',
    words: [
      { word: 'Cristiano Ronaldo', hint: 'Jubelpose' }, { word: 'Lionel Messi', hint: 'Argentinien' }, { word: 'Taylor Swift', hint: 'Freundschaftsarmband' }, { word: 'Beyoncé', hint: 'Queen' }, { word: 'Drake', hint: 'Toronto' },
      { word: 'Rihanna', hint: 'Barbados' }, { word: 'Adele', hint: 'Balladen' }, { word: 'Ed Sheeran', hint: 'Rothaarig' }, { word: 'Eminem', hint: 'Detroit' }, { word: 'Elon Musk', hint: 'Raketen' },
      { word: 'Bill Gates', hint: 'Windows' }, { word: 'Barack Obama', hint: 'Präsident' }, { word: 'Albert Einstein', hint: 'Relativität' }, { word: 'Michael Jackson', hint: 'Moonwalk' }, { word: 'Elvis Presley', hint: 'Hüftschwung' },
      { word: 'Lady Gaga', hint: 'Fleischkleid' }, { word: 'Billie Eilish', hint: 'Flüstern' }, { word: 'Kanye West', hint: 'Ego' }, { word: 'Kim Kardashian', hint: 'Reality' }, { word: 'Shakira', hint: 'Hüften' },
      { word: 'Neymar', hint: 'Schwalbe' }, { word: 'LeBron James', hint: 'Basketball' }, { word: 'Dwayne Johnson', hint: 'Wrestler' }, { word: 'Leonardo DiCaprio', hint: 'Oscar' }, { word: 'Brad Pitt', hint: 'Hollywood' },
      { word: 'Angelina Jolie', hint: 'Adoption' }, { word: 'Mr Beast', hint: 'Challenges' }, { word: 'Ariana Grande', hint: 'Pferdeschwanz' }, { word: 'Justin Bieber', hint: 'Teenieschwarm' }, { word: 'Snoop Dogg', hint: 'Westcoast' },
      { word: 'Bruno Mars', hint: 'Funk' }, { word: 'Zendaya', hint: 'Euphoria' }, { word: 'Michael Schumacher', hint: 'Rennfahrer' }, { word: 'Manuel Neuer', hint: 'Torwart' }, { word: 'Toni Kroos', hint: 'Mittelfeld' },
      { word: 'Helene Fischer', hint: 'Atemlos' }, { word: 'Capital Bra', hint: 'Deutschrap' }, { word: 'Apache 207', hint: 'Sonnenbrille' }, { word: 'Dieter Bohlen', hint: 'Jurystuhl' }, { word: 'Heidi Klum', hint: 'Topmodel' },
      { word: 'Angela Merkel', hint: 'Kanzlerjahre' }, { word: 'Arnold Schwarzenegger', hint: 'Steiermark' }, { word: 'Lewis Hamilton', hint: 'Mercedes' }, { word: 'Roger Federer', hint: 'Rasenplatz' }, { word: 'Usain Bolt', hint: 'Sprint' },
      { word: 'Rezo', hint: 'Blauhaarig' }, { word: 'Knossi', hint: 'Twitch' }, { word: 'MontanaBlack', hint: 'Streamer' }, { word: 'Olaf Scholz', hint: 'Augenklappe' }, { word: 'Robert Lewandowski', hint: 'Torjäger' }
    ],
  },
  {
    id: 'brands',
    name: 'Marken',
    icon: '🏷️',
    hint: 'Marke',
    words: [
      { word: 'Coca-Cola', hint: 'Weihnachtstruck' }, { word: 'Pepsi', hint: 'Zweiter' }, { word: 'Nike', hint: 'Laufschuh' }, { word: 'Adidas', hint: 'Herzogenaurach' }, { word: 'Apple', hint: 'Angebissen' },
      { word: 'Samsung', hint: 'Korea' }, { word: 'Google', hint: 'Suchmaschine' }, { word: 'Amazon', hint: 'Pakete' }, { word: 'Netflix', hint: 'Abspann' }, { word: 'McDonald’s', hint: 'Clown' },
      { word: 'Burger King', hint: 'Krone' }, { word: 'Starbucks', hint: 'Namensschreibfehler' }, { word: 'Ikea', hint: 'Inbusschlüssel' }, { word: 'Lego', hint: 'Barfuß' }, { word: 'Ferrari', hint: 'Knallrot' },
      { word: 'Lamborghini', hint: 'Stier' }, { word: 'BMW', hint: 'Blinker' }, { word: 'Mercedes', hint: 'Stern' }, { word: 'Tesla', hint: 'Autopilot' }, { word: 'Porsche', hint: 'Stuttgart' },
      { word: 'Rolex', hint: 'Statussymbol' }, { word: 'Gucci', hint: 'Rapperzeile' }, { word: 'Louis Vuitton', hint: 'Monogramm' }, { word: 'Chanel', hint: 'Parfüm' }, { word: 'Red Bull', hint: 'Flügel' },
      { word: 'Nutella', hint: 'Streitfrage' }, { word: 'Lindt', hint: 'Goldhase' }, { word: 'Spotify', hint: 'Jahresrückblick' }, { word: 'YouTube', hint: 'Abonnieren' }, { word: 'Instagram', hint: 'Filter' },
      { word: 'TikTok', hint: 'Tänze' }, { word: 'PlayStation', hint: 'Exklusivtitel' }, { word: 'Xbox', hint: 'Microsoft' }, { word: 'Nintendo', hint: 'Klempner' }, { word: 'Haribo', hint: 'Bonn' },
      { word: 'Milka', hint: 'Lila' }, { word: 'Ritter Sport', hint: 'Quadratisch' }, { word: 'Volkswagen', hint: 'Käfer' }, { word: 'Audi', hint: 'Ringe' }, { word: 'Aldi', hint: 'Mittelgang' },
      { word: 'Lidl', hint: 'Backautomat' }, { word: 'Zalando', hint: 'Schrei' }, { word: 'Snapchat', hint: 'Geist' }, { word: 'WhatsApp', hint: 'Haken' }, { word: 'Disney', hint: 'Micky' },
      { word: 'Shell', hint: 'Muschel' }, { word: 'Lufthansa', hint: 'Kranich' }, { word: 'Deutsche Bahn', hint: 'Sitzplatzreservierung' }, { word: 'Fanta', hint: 'Orange' }, { word: 'Oreo', hint: 'Eintunken' }
    ],
  },
  {
    id: 'sport',
    name: 'Sport',
    icon: '⚽',
    hint: 'Sport',
    words: [
      { word: 'Fußball', hint: 'Abseits' }, { word: 'Basketball', hint: 'Korb' }, { word: 'Tennis', hint: 'Wimbledon' }, { word: 'Golf', hint: 'Handicap' }, { word: 'Boxen', hint: 'Ringrichter' },
      { word: 'Schwimmen', hint: 'Startblock' }, { word: 'Skifahren', hint: 'Lift' }, { word: 'Snowboarden', hint: 'Halfpipe' }, { word: 'Surfen', hint: 'Welle' }, { word: 'Klettern', hint: 'Sicherung' },
      { word: 'Reiten', hint: 'Sattel' }, { word: 'Turnen', hint: 'Barren' }, { word: 'Volleyball', hint: 'Baggern' }, { word: 'Handball', hint: 'Kreisläufer' }, { word: 'Eishockey', hint: 'Puck' },
      { word: 'Baseball', hint: 'Homerun' }, { word: 'Rugby', hint: 'Gedränge' }, { word: 'Cricket', hint: 'Commonwealth' }, { word: 'Bogenschießen', hint: 'Zielscheibe' }, { word: 'Fechten', hint: 'Maske' },
      { word: 'Judo', hint: 'Gürtelfarbe' }, { word: 'Karate', hint: 'Bretter' }, { word: 'Ringen', hint: 'Matte' }, { word: 'Marathon', hint: 'Kilometer' }, { word: 'Radfahren', hint: 'Trikot' },
      { word: 'Rudern', hint: 'Steuermann' }, { word: 'Segeln', hint: 'Wind' }, { word: 'Tauchen', hint: 'Sauerstoff' }, { word: 'Darts', hint: 'Kneipe' }, { word: 'Billard', hint: 'Kreide' },
      { word: 'Bowling', hint: 'Leihschuhe' }, { word: 'Tischtennis', hint: 'Keller' }, { word: 'Skateboarden', hint: 'Rampe' }, { word: 'Yoga', hint: 'Atemübung' }, { word: 'Leichtathletik', hint: 'Hürden' },
      { word: 'Formel 1', hint: 'Boxenstopp' }, { word: 'Biathlon', hint: 'Gewehr' }, { word: 'Eiskunstlauf', hint: 'Pirouette' }, { word: 'Kegeln', hint: 'Vereinsabend' }, { word: 'Badminton', hint: 'Feder' },
      { word: 'Squash', hint: 'Rückwand' }, { word: 'Triathlon', hint: 'Wechselzone' }, { word: 'Gewichtheben', hint: 'Stemmen' }, { word: 'Zumba', hint: 'Fitnesskurs' }, { word: 'Schach', hint: 'Bedenkzeit' },
      { word: 'Angeln', hint: 'Geduld' }, { word: 'Parkour', hint: 'Hindernisse' }, { word: 'Wandern', hint: 'Blasen' }, { word: 'Curling', hint: 'Zielkreis' }, { word: 'Sumo', hint: 'Gewichtsklasse' }
    ],
  },
  {
    id: 'countries',
    name: 'Länder & Städte',
    icon: '🌍',
    hint: 'Ort',
    words: [
      { word: 'Deutschland', hint: 'Mülltrennung' }, { word: 'Frankreich', hint: 'Eiffelturm' }, { word: 'Italien', hint: 'Stiefel' }, { word: 'Spanien', hint: 'Stierkampf' }, { word: 'England', hint: 'Linksverkehr' },
      { word: 'USA', hint: 'Sternenbanner' }, { word: 'Japan', hint: 'Schriftzeichen' }, { word: 'China', hint: 'Milliarde' }, { word: 'Brasilien', hint: 'Karneval' }, { word: 'Australien', hint: 'Outback' },
      { word: 'Kanada', hint: 'Ahorn' }, { word: 'Mexiko', hint: 'Sombrero' }, { word: 'Ägypten', hint: 'Pharao' }, { word: 'Indien', hint: 'Bollywood' }, { word: 'Russland', hint: 'Kreml' },
      { word: 'Griechenland', hint: 'Säulen' }, { word: 'Türkei', hint: 'Basar' }, { word: 'Norwegen', hint: 'Fjorde' }, { word: 'Berlin', hint: 'Fernsehturm' }, { word: 'Paris', hint: 'Laufsteg' },
      { word: 'London', hint: 'Doppeldecker' }, { word: 'New York', hint: 'Wolkenkratzer' }, { word: 'Tokio', hint: 'Anime' }, { word: 'Rom', hint: 'Papst' }, { word: 'Madrid', hint: 'Real' },
      { word: 'Dubai', hint: 'Scheichs' }, { word: 'Amsterdam', hint: 'Grachten' }, { word: 'Barcelona', hint: 'Tapas' }, { word: 'Istanbul', hint: 'Bosporus' }, { word: 'Sydney', hint: 'Opernhaus' },
      { word: 'Las Vegas', hint: 'Jackpot' }, { word: 'Wien', hint: 'Kaffeehaus' }, { word: 'Zürich', hint: 'Banken' }, { word: 'Rio de Janeiro', hint: 'Zuckerhut' }, { word: 'Portugal', hint: 'Kork' },
      { word: 'Niederlande', hint: 'Tulpen' }, { word: 'Schweiz', hint: 'Neutralität' }, { word: 'Österreich', hint: 'Mozartkugeln' }, { word: 'Polen', hint: 'Pierogi' }, { word: 'Schweden', hint: 'Elche' },
      { word: 'Island', hint: 'Geysire' }, { word: 'Thailand', hint: 'Backpacker' }, { word: 'Marokko', hint: 'Couscous' }, { word: 'Argentinien', hint: 'Tango' }, { word: 'Hawaii', hint: 'Blumenkette' },
      { word: 'Grönland', hint: 'Gletscher' }, { word: 'Hamburg', hint: 'Reeperbahn' }, { word: 'München', hint: 'Weißwurst' }, { word: 'Köln', hint: 'Kölsch' }, { word: 'Venedig', hint: 'Hochwasser' }
    ],
  },
  {
    id: 'body',
    name: 'Körperteile',
    icon: '🫀',
    hint: 'Körper',
    words: [
      { word: 'Kopf', hint: 'Nicken' }, { word: 'Auge', hint: 'Blinzeln' }, { word: 'Nase', hint: 'Riechen' }, { word: 'Mund', hint: 'Lippenstift' }, { word: 'Ohr', hint: 'Lauschen' },
      { word: 'Zunge', hint: 'Schmecken' }, { word: 'Zahn', hint: 'Fee' }, { word: 'Haar', hint: 'Frisur' }, { word: 'Hals', hint: 'Schal' }, { word: 'Schulter', hint: 'Zucken' },
      { word: 'Arm', hint: 'Winken' }, { word: 'Ellbogen', hint: 'Anstoßen' }, { word: 'Hand', hint: 'Greifen' }, { word: 'Finger', hint: 'Zeigen' }, { word: 'Daumen', hint: 'Trampen' },
      { word: 'Bauch', hint: 'Grummeln' }, { word: 'Rücken', hint: 'Massage' }, { word: 'Bein', hint: 'Laufen' }, { word: 'Knie', hint: 'Beugen' }, { word: 'Fuß', hint: 'Socken' },
      { word: 'Zeh', hint: 'Bettkante' }, { word: 'Ferse', hint: 'Sehne' }, { word: 'Herz', hint: 'Verliebt' }, { word: 'Gehirn', hint: 'Denken' }, { word: 'Lunge', hint: 'Atmen' },
      { word: 'Magen', hint: 'Knurren' }, { word: 'Leber', hint: 'Entgiftung' }, { word: 'Rippe', hint: 'Prellung' }, { word: 'Wirbelsäule', hint: 'Aufrecht' }, { word: 'Kinn', hint: 'Bart' },
      { word: 'Wange', hint: 'Erröten' }, { word: 'Augenbraue', hint: 'Zupfen' }, { word: 'Wimper', hint: 'Tusche' }, { word: 'Nabel', hint: 'Mitte' }, { word: 'Stirn', hint: 'Falten' },
      { word: 'Nacken', hint: 'Verspannt' }, { word: 'Handgelenk', hint: 'Armband' }, { word: 'Knöchel', hint: 'Umknicken' }, { word: 'Wade', hint: 'Krampf' }, { word: 'Oberschenkel', hint: 'Kniebeuge' },
      { word: 'Po', hint: 'Polster' }, { word: 'Hüfte', hint: 'Schwung' }, { word: 'Niere', hint: 'Bohne' }, { word: 'Blase', hint: 'Dringend' }, { word: 'Muskel', hint: 'Anspannen' },
      { word: 'Knochen', hint: 'Bruch' }, { word: 'Haut', hint: 'Sonnenbrand' }, { word: 'Blut', hint: 'Spende' }, { word: 'Nerven', hint: 'Kitzel' }, { word: 'Zwerchfell', hint: 'Lachkrampf' }
    ],
  },
  {
    id: 'household',
    name: 'Haushalt',
    icon: '🏠',
    hint: 'Gegenstand',
    words: [
      { word: 'Kühlschrank', hint: 'Restebeutel' }, { word: 'Waschmaschine', hint: 'Schleudern' }, { word: 'Staubsauger', hint: 'Sonntagsverbot' }, { word: 'Mikrowelle', hint: 'Aufwärmen' }, { word: 'Toaster', hint: 'Schlitze' },
      { word: 'Herd', hint: 'Platten' }, { word: 'Backofen', hint: 'Vorheizen' }, { word: 'Wasserkocher', hint: 'Pfeifen' }, { word: 'Bügeleisen', hint: 'Falten' }, { word: 'Föhn', hint: 'Lärm' },
      { word: 'Fernseher', hint: 'Fernbedienung' }, { word: 'Sofa', hint: 'Lümmeln' }, { word: 'Bett', hint: 'Matratze' }, { word: 'Schrank', hint: 'Kleiderbügel' }, { word: 'Tisch', hint: 'Esszimmer' },
      { word: 'Stuhl', hint: 'Lehne' }, { word: 'Teppich', hint: 'Fransen' }, { word: 'Vorhang', hint: 'Zuziehen' }, { word: 'Spülmaschine', hint: 'Einräumen' }, { word: 'Besen', hint: 'Fegen' },
      { word: 'Eimer', hint: 'Wischwasser' }, { word: 'Schwamm', hint: 'Abwasch' }, { word: 'Handtuch', hint: 'Frottee' }, { word: 'Kissen', hint: 'Federn' }, { word: 'Decke', hint: 'Kuscheln' },
      { word: 'Wecker', hint: 'Snooze' }, { word: 'Kerze', hint: 'Docht' }, { word: 'Bilderrahmen', hint: 'Aufhängen' }, { word: 'Blumentopf', hint: 'Untersetzer' }, { word: 'Mülleimer', hint: 'Rausbringen' },
      { word: 'Steckdose', hint: 'Kindersicherung' }, { word: 'Türklinke', hint: 'Drücken' }, { word: 'Klopapier', hint: 'Hamsterkauf' }, { word: 'Waschbecken', hint: 'Abfluss' }, { word: 'Dusche', hint: 'Singen' },
      { word: 'Badewanne', hint: 'Schaumbad' }, { word: 'Heizung', hint: 'Thermostat' }, { word: 'Regal', hint: 'Fächer' }, { word: 'Nachttisch', hint: 'Schublade' }, { word: 'Gießkanne', hint: 'Balkon' },
      { word: 'Wäscheständer', hint: 'Klammern' }, { word: 'Gefriertruhe', hint: 'Abtauen' }, { word: 'Kaffeemaschine', hint: 'Entkalken' }, { word: 'Mixer', hint: 'Smoothie' }, { word: 'Pfanne', hint: 'Antihaft' },
      { word: 'Topf', hint: 'Überkochen' }, { word: 'Schneidebrett', hint: 'Gemüse' }, { word: 'Korkenzieher', hint: 'Spirale' }, { word: 'Dosenöffner', hint: 'Konserven' }, { word: 'Rasenmäher', hint: 'Mittagsruhe' }
    ],
  },
  {
    id: 'school',
    name: 'Schule',
    icon: '🎒',
    hint: 'Schule',
    words: [
      { word: 'Tafel', hint: 'Quietschen' }, { word: 'Kreide', hint: 'Staub' }, { word: 'Heft', hint: 'Linien' }, { word: 'Stift', hint: 'Mine' }, { word: 'Radiergummi', hint: 'Ausbessern' },
      { word: 'Lineal', hint: 'Zentimeter' }, { word: 'Schere', hint: 'Schneiden' }, { word: 'Kleber', hint: 'Basteln' }, { word: 'Rucksack', hint: 'Schleppen' }, { word: 'Pausenbrot', hint: 'Tauschen' },
      { word: 'Klassenzimmer', hint: 'Sitzplan' }, { word: 'Lehrer', hint: 'Pult' }, { word: 'Hausaufgabe', hint: 'Ausrede' }, { word: 'Prüfung', hint: 'Schwitzen' }, { word: 'Zeugnis', hint: 'Unterschrift' },
      { word: 'Note', hint: 'Verhandeln' }, { word: 'Mathe', hint: 'Zahlen' }, { word: 'Deutsch', hint: 'Diktat' }, { word: 'Englisch', hint: 'Vokabeln' }, { word: 'Chemie', hint: 'Experimente' },
      { word: 'Biologie', hint: 'Zellen' }, { word: 'Physik', hint: 'Formeln' }, { word: 'Geschichte', hint: 'Jahreszahlen' }, { word: 'Sportunterricht', hint: 'Umkleide' }, { word: 'Pause', hint: 'Klingel' },
      { word: 'Schulhof', hint: 'Toben' }, { word: 'Bibliothek', hint: 'Regale' }, { word: 'Turnhalle', hint: 'Sprossenwand' }, { word: 'Mensa', hint: 'Tablett' }, { word: 'Direktor', hint: 'Vorladung' },
      { word: 'Spickzettel', hint: 'Erwischt' }, { word: 'Taschenrechner', hint: 'Tasten' }, { word: 'Globus', hint: 'Drehen' }, { word: 'Federmäppchen', hint: 'Reißverschluss' }, { word: 'Klassenfahrt', hint: 'Jugendherberge' },
      { word: 'Stundenplan', hint: 'Fächer' }, { word: 'Melden', hint: 'Handzeichen' }, { word: 'Nachsitzen', hint: 'Strafe' }, { word: 'Abschlussball', hint: 'Kleid' }, { word: 'Referat', hint: 'Nervosität' },
      { word: 'Abitur', hint: 'Abschluss' }, { word: 'Hitzefrei', hint: 'Jubel' }, { word: 'Streber', hint: 'Musterschüler' }, { word: 'Banknachbar', hint: 'Abschreiben' }, { word: 'Kunst', hint: 'Malkasten' },
      { word: 'Elternabend', hint: 'Peinlich' }, { word: 'Vertretungsstunde', hint: 'Ausfall' }, { word: 'Schulbus', hint: 'Haltestelle' }, { word: 'Zirkel', hint: 'Kreise' }, { word: 'Füller', hint: 'Tinte' }
    ],
  },
  {
    id: 'tech',
    name: 'Technik',
    icon: '📱',
    hint: 'Technik',
    words: [
      { word: 'Smartphone', hint: 'Displayriss' }, { word: 'Laptop', hint: 'Klappen' }, { word: 'Tablet', hint: 'Flach' }, { word: 'Kopfhörer', hint: 'Kabelsalat' }, { word: 'Kamera', hint: 'Objektiv' },
      { word: 'Drohne', hint: 'Luftaufnahme' }, { word: 'Roboter', hint: 'Fließband' }, { word: 'Ladekabel', hint: 'Ausleihen' }, { word: 'Powerbank', hint: 'Unterwegs' }, { word: 'Router', hint: 'Neustarten' },
      { word: 'Bluetooth', hint: 'Koppeln' }, { word: 'WLAN', hint: 'Gästezugang' }, { word: 'USB-Stick', hint: 'Verlieren' }, { word: 'Festplatte', hint: 'Speicherplatz' }, { word: 'Grafikkarte', hint: 'Preisanstieg' },
      { word: 'Prozessor', hint: 'Kerne' }, { word: 'Bildschirm', hint: 'Pixel' }, { word: 'Tastatur', hint: 'Tippen' }, { word: 'Maus', hint: 'Klicken' }, { word: 'Drucker', hint: 'Papierstau' },
      { word: 'Scanner', hint: 'Einlesen' }, { word: 'Smartwatch', hint: 'Schrittzahl' }, { word: 'VR-Brille', hint: 'Schwindel' }, { word: 'Konsole', hint: 'Zocken' }, { word: 'Controller', hint: 'Vibration' },
      { word: 'Beamer', hint: 'Abdunkeln' }, { word: 'Lautsprecher', hint: 'Bass' }, { word: 'Mikrofon', hint: 'Aufnahme' }, { word: 'GPS', hint: 'Satelliten' }, { word: 'Akku', hint: 'Steckdose' },
      { word: 'App', hint: 'Herunterladen' }, { word: 'Passwort', hint: 'Vergessen' }, { word: 'Cloud', hint: 'Hochladen' }, { word: 'Emoji', hint: 'Missverständnis' }, { word: 'Algorithmus', hint: 'Empfehlungen' },
      { word: 'KI', hint: 'Prompt' }, { word: 'Virus', hint: 'Infiziert' }, { word: 'Update', hint: 'Ungünstig' }, { word: 'Browser', hint: 'Tabs' }, { word: 'E-Mail', hint: 'Posteingang' },
      { word: 'Bitcoin', hint: 'Kursschwankung' }, { word: 'Webcam', hint: 'Abgeklebt' }, { word: 'Server', hint: 'Rechenzentrum' }, { word: 'Touchscreen', hint: 'Fingerabdrücke' }, { word: 'Hologramm', hint: 'Zukunftsvision' },
      { word: 'Joystick', hint: 'Arcade' }, { word: 'E-Scooter', hint: 'Gehweg' }, { word: '3D-Drucker', hint: 'Schichten' }, { word: 'Antenne', hint: 'Empfang' }, { word: 'Screenshot', hint: 'Beweis' }
    ],
  },
  {
    id: 'funny',
    name: 'Quatsch & Lustig',
    icon: '🤪',
    hint: 'Quatsch',
    words: [
      { word: 'Furz', hint: 'Bettdecke' }, { word: 'Nasenpopel', hint: 'Ampel' }, { word: 'Unterhose', hint: 'Drunter' }, { word: 'Schnurrbart', hint: 'Zwirbeln' }, { word: 'Gummiente', hint: 'Quietschen' },
      { word: 'Clown', hint: 'Kinderangst' }, { word: 'Einhorn', hint: 'Regenbogen' }, { word: 'Zwerg', hint: 'Sieben' }, { word: 'Zombie', hint: 'Untot' }, { word: 'Alien', hint: 'UFO' },
      { word: 'Nacktschnecke', hint: 'Schleimspur' }, { word: 'Schnabeltier', hint: 'Mischwesen' }, { word: 'Toilette', hint: 'Spülung' }, { word: 'Windel', hint: 'Wickeln' }, { word: 'Zahnspange', hint: 'Draht' },
      { word: 'Perücke', hint: 'Verrutschen' }, { word: 'Glatze', hint: 'Spiegelnd' }, { word: 'Doppelkinn', hint: 'Kameraperspektive' }, { word: 'Schluckauf', hint: 'Erschrecken' }, { word: 'Niesen', hint: 'Segenswunsch' },
      { word: 'Kitzeln', hint: 'Wehrlos' }, { word: 'Pupsen', hint: 'Leugnen' }, { word: 'Grimasse', hint: 'Verziehen' }, { word: 'Selfie', hint: 'Duckface' }, { word: 'Verstopfung', hint: 'Pflaumen' },
      { word: 'Ohrwurm', hint: 'Dauerschleife' }, { word: 'Fettnäpfchen', hint: 'Reintreten' }, { word: 'Warze', hint: 'Hexe' }, { word: 'Schweißfleck', hint: 'Vorstellungsgespräch' }, { word: 'Achselhaar', hint: 'Rasieren' },
      { word: 'Sabber', hint: 'Mittagsschlaf' }, { word: 'Rülpsen', hint: 'Limo' }, { word: 'Bauchnabelfussel', hint: 'Flusen' }, { word: 'Kuscheltier', hint: 'Teddy' }, { word: 'Stinkefinger', hint: 'Beleidigung' },
      { word: 'Klobrille', hint: 'Hochklappen' }, { word: 'Furzkissen', hint: 'Scherzartikel' }, { word: 'Pickel', hint: 'Ausdrücken' }, { word: 'Mundgeruch', hint: 'Kaugummi' }, { word: 'Schnarchen', hint: 'Getrennt' },
      { word: 'Stolpern', hint: 'Bordstein' }, { word: 'Bananenschale', hint: 'Ausrutschen' }, { word: 'Juckreiz', hint: 'Kratzen' }, { word: 'Käsefüße', hint: 'Turnschuhe' }, { word: 'Milchbart', hint: 'Oberlippe' },
      { word: 'Wackelzahn', hint: 'Ziehen' }, { word: 'Lachanfall', hint: 'Unpassend' }, { word: 'Gähnen', hint: 'Ansteckend' }, { word: 'Nasenhaar', hint: 'Pinzette' }, { word: 'Kichern', hint: 'Hinterletzte' }
    ],
  },
  {
    id: 'party',
    name: 'Party',
    icon: '🎉',
    hint: 'Party',
    words: [
      { word: 'Bier', hint: 'Zapfhahn' }, { word: 'Cocktail', hint: 'Schirmchen' }, { word: 'Shot', hint: 'Kippen' }, { word: 'Tequila', hint: 'Salzrand' }, { word: 'Wodka', hint: 'Geschmacklos' },
      { word: 'Sekt', hint: 'Korken' }, { word: 'Bierpong', hint: 'Becher' }, { word: 'Tanzfläche', hint: 'Parkett' }, { word: 'DJ', hint: 'Wunschlied' }, { word: 'Discokugel', hint: 'Glitzern' },
      { word: 'Karaoke', hint: 'Mitsingen' }, { word: 'Konfetti', hint: 'Wochenlang' }, { word: 'Luftballon', hint: 'Platzen' }, { word: 'Geburtstag', hint: 'Ständchen' }, { word: 'Torte', hint: 'Etagen' },
      { word: 'Feuerwerk', hint: 'Hundeangst' }, { word: 'Trinkspiel', hint: 'Regeln' }, { word: 'Kater', hint: 'Reue' }, { word: 'Absturz', hint: 'Filmriss' }, { word: 'Nachtclub', hint: 'Warteschlange' },
      { word: 'Türsteher', hint: 'Abgewiesen' }, { word: 'Wackelpudding', hint: 'Wabbelig' }, { word: 'Flunkyball', hint: 'Umkippen' }, { word: 'Kostüm', hint: 'Verkleiden' }, { word: 'Junggesellenabschied', hint: 'Bräutigam' },
      { word: 'Silvester', hint: 'Countdown' }, { word: 'Festival', hint: 'Bändchen' }, { word: 'Lagerfeuer', hint: 'Stockbrot' }, { word: 'Grillen', hint: 'Kohle' }, { word: 'Wunderkerze', hint: 'Funkeln' },
      { word: 'Anstoßen', hint: 'Prost' }, { word: 'Tanzen', hint: 'Rhythmus' }, { word: 'Betrunken', hint: 'Lallen' }, { word: 'Afterparty', hint: 'Sonnenaufgang' }, { word: 'Bowle', hint: 'Früchte' },
      { word: 'Jägermeister', hint: 'Hirsch' }, { word: 'Aperol', hint: 'Sommerabend' }, { word: 'Limbo', hint: 'Stange' }, { word: 'Polonaise', hint: 'Reihe' }, { word: 'Einladung', hint: 'Gästeliste' },
      { word: 'Luftschlangen', hint: 'Pusten' }, { word: 'Piñata', hint: 'Augenbinde' }, { word: 'Flaschendrehen', hint: 'Küssen' }, { word: 'Mottoparty', hint: 'Dresscode' }, { word: 'Katerfrühstück', hint: 'Aspirin' },
      { word: 'Garderobe', hint: 'Nummernschein' }, { word: 'Barhocker', hint: 'Tresen' }, { word: 'Vorglühen', hint: 'Sparen' }, { word: 'Heimweg', hint: 'Taxi' }, { word: 'Sektdusche', hint: 'Podium' }
    ],
  },
  {
    id: 'adult',
    name: '18+ Anzüglich',
    icon: '🔞',
    hint: '18+',
    adult: true,
    words: [
      { word: 'Kondom', hint: 'Apotheke' }, { word: 'Dessous', hint: 'Spitze' }, { word: 'Tanga', hint: 'Knapp' }, { word: 'Höschen', hint: 'Seide' }, { word: 'Reizwäsche', hint: 'Anlass' },
      { word: 'Nachthemd', hint: 'Schlafzimmer' }, { word: 'Kussmund', hint: 'Lippenstift' }, { word: 'Knutschfleck', hint: 'Rollkragen' }, { word: 'Zungenkuss', hint: 'Französisch' }, { word: 'Flirt', hint: 'Zwinkern' },
      { word: 'One-Night-Stand', hint: 'Aufwachen' }, { word: 'Tinder', hint: 'Wischen' }, { word: 'Blind Date', hint: 'Überraschung' }, { word: 'Verführung', hint: 'Blicke' }, { word: 'Techtelmechtel', hint: 'Heimlich' },
      { word: 'Vorspiel', hint: 'Aufwärmen' }, { word: 'Rotlichtviertel', hint: 'Reeperbahn' }, { word: 'Stripclub', hint: 'Scheine' }, { word: 'Poledance', hint: 'Stange' }, { word: 'Handschellen', hint: 'Bettpfosten' },
      { word: 'Peitsche', hint: 'Knallen' }, { word: 'Whirlpool', hint: 'Blubbern' }, { word: 'Massageöl', hint: 'Rücken' }, { word: 'Liebesbrief', hint: 'Parfümiert' }, { word: 'Playboy', hint: 'Häschen' },
      { word: 'Aktfoto', hint: 'Malkurs' }, { word: 'Kamasutra', hint: 'Indien' }, { word: 'Junggesellinnenabschied', hint: 'Schleier' }, { word: 'Schäferstündchen', hint: 'Mittags' }, { word: 'Bikini', hint: 'Streifen' },
      { word: 'Push-up', hint: 'Ausschnitt' }, { word: 'Rendezvous', hint: 'Kerzenlicht' }, { word: 'Seitensprung', hint: 'Ertappt' }, { word: 'Wackelpo', hint: 'Twerken' }, { word: 'Strapse', hint: 'Oberschenkel' },
      { word: 'Korsett', hint: 'Schnüren' }, { word: 'Flitterwochen', hint: 'Suite' }, { word: 'Bettgeflüster', hint: 'Kopfkissen' }, { word: 'Aphrodisiakum', hint: 'Austern' }, { word: 'Striptease', hint: 'Langsam' },
      { word: 'Nacktbaden', hint: 'Mondschein' }, { word: 'FKK', hint: 'Ostsee' }, { word: 'Anbaggern', hint: 'Anmachspruch' }, { word: 'Erotikroman', hint: 'Nachttisch' }, { word: 'Silikon', hint: 'Operation' },
      { word: 'Leidenschaft', hint: 'Flammen' }, { word: 'Liebesnest', hint: 'Versteck' }, { word: 'Rosenblätter', hint: 'Badewanne' }, { word: 'Candle-Light-Dinner', hint: 'Zweisamkeit' }, { word: 'Herzklopfen', hint: 'Aufregung' }
    ],
  },
  {
    id: 'music',
    name: 'Musik',
    icon: '🎵',
    hint: 'Musik',
    words: [
      { word: 'Gitarre', hint: 'Schwielen' }, { word: 'Klavier', hint: 'Umzugshelfer' }, { word: 'Schlagzeug', hint: 'Nachbarbeschwerde' }, { word: 'Geige', hint: 'Kinnstütze' }, { word: 'Trompete', hint: 'Blech' },
      { word: 'Flöte', hint: 'Grundschule' }, { word: 'Saxofon', hint: 'Barmusik' }, { word: 'Cello', hint: 'Sitzend' }, { word: 'Harfe', hint: 'Engel' }, { word: 'Mikrofon', hint: 'Rückkopplung' },
      { word: 'Notenblatt', hint: 'Ständer' }, { word: 'Plattenspieler', hint: 'Knistern' }, { word: 'Konzert', hint: 'Zugabe' }, { word: 'Oper', hint: 'Fernglas' }, { word: 'Band', hint: 'Proberaum' },
      { word: 'Chor', hint: 'Stimmlage' }, { word: 'Orchester', hint: 'Graben' }, { word: 'Rap', hint: 'Reime' }, { word: 'Rock', hint: 'Lederjacke' }, { word: 'Pop', hint: 'Charts' },
      { word: 'Techno', hint: 'Rave' }, { word: 'Jazz', hint: 'Improvisation' }, { word: 'Klassik', hint: 'Beethoven' }, { word: 'Reggae', hint: 'Jamaika' }, { word: 'Metal', hint: 'Headbangen' },
      { word: 'Schlager', hint: 'Ballermann' }, { word: 'Ohrwurm', hint: 'Radio' }, { word: 'Playlist', hint: 'Shuffle' }, { word: 'Album', hint: 'Cover' }, { word: 'Single', hint: 'Auskopplung' },
      { word: 'Refrain', hint: 'Mitgrölen' }, { word: 'Beat', hint: 'Kopfnicken' }, { word: 'Dirigent', hint: 'Taktstock' }, { word: 'Akkord', hint: 'Griffe' }, { word: 'Bass', hint: 'Wummern' },
      { word: 'Ukulele', hint: 'Hawaii' }, { word: 'Dudelsack', hint: 'Schottland' }, { word: 'Akkordeon', hint: 'Quetschen' }, { word: 'Triangel', hint: 'Nebenrolle' }, { word: 'Xylophon', hint: 'Stäbe' },
      { word: 'Panflöte', hint: 'Fußgängerzone' }, { word: 'Mundharmonika', hint: 'Hosentasche' }, { word: 'Sänger', hint: 'Stimmbänder' }, { word: 'Hymne', hint: 'Aufstehen' }, { word: 'Wiegenlied', hint: 'Einschlafen' },
      { word: 'Weihnachtslied', hint: 'Dezember' }, { word: 'Konzertkarte', hint: 'Ausverkauft' }, { word: 'Boygroup', hint: 'Neunziger' }, { word: 'Autotune', hint: 'Roboterstimme' }, { word: 'Musical', hint: 'Broadway' },
      { word: 'Jodeln', hint: 'Almhütte' }, { word: 'Straßenmusiker', hint: 'Hut' }
    ],
  },
  {
    id: 'crazy',
    name: 'Verrückt',
    icon: '🤪',
    hint: 'Verrückt',
    words: [
      { word: 'Backpfeifengesicht', hint: 'Ohrfeige' }, { word: 'Kummerspeck', hint: 'Trennung' }, { word: 'Treppenwitz', hint: 'Zuspät' }, { word: 'Schnapsidee', hint: 'Betrunken' }, { word: 'Kuddelmuddel', hint: 'Durcheinander' },
      { word: 'Firlefanz', hint: 'Überflüssig' }, { word: 'Schabernack', hint: 'Streich' }, { word: 'Tohuwabohu', hint: 'Bibel' }, { word: 'Hokuspokus', hint: 'Abrakadabra' }, { word: 'Schlawiner', hint: 'Gauner' },
      { word: 'Dreikäsehoch', hint: 'Knirps' }, { word: 'Hüftgold', hint: 'Röllchen' }, { word: 'Zappelphilipp', hint: 'Unruhig' }, { word: 'Erbsenzähler', hint: 'Kleinlich' }, { word: 'Schluckspecht', hint: 'Trinker' },
      { word: 'Naseweis', hint: 'Vorlaut' }, { word: 'Sitzfleisch', hint: 'Durchhalten' }, { word: 'Pantoffelheld', hint: 'Ehemann' }, { word: 'Sauklaue', hint: 'Handschrift' }, { word: 'Muskelkater', hint: 'Anfänger' },
      { word: 'Katzenjammer', hint: 'Reue' }, { word: 'Weltschmerz', hint: 'Melancholie' }, { word: 'Torschlusspanik', hint: 'Alter' }, { word: 'Verschlimmbessern', hint: 'Reparatur' }, { word: 'Gedankenkarussell', hint: 'Grübeln' },
      { word: 'Schweinehund', hint: 'Überwinden' }, { word: 'Sommerloch', hint: 'Nachrichten' }, { word: 'Schnappatmung', hint: 'Empörung' }, { word: 'Hexenschuss', hint: 'Bücken' }, { word: 'Quatschkopf', hint: 'Blödsinn' },
      { word: 'Wirrwarr', hint: 'Fäden' }, { word: 'Kladderadatsch', hint: 'Zusammenbruch' }, { word: 'Kabelsalat', hint: 'Schreibtisch' }, { word: 'Zungenbrecher', hint: 'Aussprache' }, { word: 'Luftschloss', hint: 'Träumerei' },
      { word: 'Drahtesel', hint: 'Zweirad' }, { word: 'Extrawurst', hint: 'Sonderwunsch' }, { word: 'Donnerbalken', hint: 'Plumpsklo' }, { word: 'Schnickschnack', hint: 'Deko' }, { word: 'Larifari', hint: 'Halbherzig' },
      { word: 'Mumpitz', hint: 'Erfunden' }, { word: 'Fisimatenten', hint: 'Ausflüchte' }, { word: 'Zinnober', hint: 'Aufheben' }, { word: 'Sperenzchen', hint: 'Zicken' }, { word: 'Suppenkasper', hint: 'Struwwelpeter' },
      { word: 'Nervensäge', hint: 'Geschwister' }, { word: 'Angsthase', hint: 'Mutprobe' }, { word: 'Purzelbaum', hint: 'Wiese' }, { word: 'Krawallschachtel', hint: 'Randale' }, { word: 'Trantüte', hint: 'Trödeln' }
    ],
  },
];
