import type { Category } from './types';

// Hint-Regeln (siehe words.test.ts):
// - genau ein Wort pro Hint
// - Hint verrät das Wort nicht, ist aber konkret genug zum Eingrenzen
// - kein Hint gleich dem Kategorienamen/-hint, pro Kategorie max. 2x derselbe Hint
export const categoriesDe: Category[] = [
  {
    id: 'easy',
    name: 'Einfache Wörter',
    icon: '🎲',
    hint: 'Alltag',
    words: [
      { word: 'Apfel', hint: 'Obst' }, { word: 'Hund', hint: 'Leine' }, { word: 'Sonne', hint: 'Himmel' }, { word: 'Buch', hint: 'Seiten' }, { word: 'Stuhl', hint: 'Sitzen' },
      { word: 'Wasser', hint: 'Durst' }, { word: 'Fenster', hint: 'Glas' }, { word: 'Schuh', hint: 'Fuß' }, { word: 'Baum', hint: 'Wald' }, { word: 'Auto', hint: 'Straße' },
      { word: 'Tasse', hint: 'Kaffee' }, { word: 'Brille', hint: 'Sehen' }, { word: 'Schlüssel', hint: 'Schloss' }, { word: 'Uhr', hint: 'Zeit' }, { word: 'Kissen', hint: 'Weich' },
      { word: 'Löffel', hint: 'Suppe' }, { word: 'Regen', hint: 'Nass' }, { word: 'Berg', hint: 'Gipfel' }, { word: 'Brücke', hint: 'Fluss' }, { word: 'Kerze', hint: 'Flamme' },
      { word: 'Spiegel', hint: 'Badezimmer' }, { word: 'Teppich', hint: 'Boden' }, { word: 'Zahnbürste', hint: 'Borsten' }, { word: 'Regenschirm', hint: 'Trocken' }, { word: 'Bleistift', hint: 'Zeichnen' },
      { word: 'Ballon', hint: 'Helium' }, { word: 'Koffer', hint: 'Packen' }, { word: 'Handschuh', hint: 'Winter' }, { word: 'Wecker', hint: 'Klingeln' }, { word: 'Gabel', hint: 'Besteck' },
      { word: 'Seife', hint: 'Schaum' }, { word: 'Lampe', hint: 'Licht' }, { word: 'Fahrrad', hint: 'Pedale' }, { word: 'Wolke', hint: 'Schäfchen' }, { word: 'Blume', hint: 'Duft' },
      { word: 'Feuer', hint: 'Heiß' }, { word: 'Leiter', hint: 'Sprossen' }, { word: 'Zelt', hint: 'Camping' }, { word: 'Kamm', hint: 'Haare' }, { word: 'Knopf', hint: 'Hemd' },
      { word: 'Seil', hint: 'Knoten' }, { word: 'Kalender', hint: 'Datum' }, { word: 'Briefmarke', hint: 'Post' }, { word: 'Mütze', hint: 'Kopf' }, { word: 'Socke', hint: 'Paar' },
      { word: 'Nagel', hint: 'Hammer' }, { word: 'Taschenlampe', hint: 'Dunkelheit' }, { word: 'Zeitung', hint: 'Nachrichten' }, { word: 'Geschenk', hint: 'Schleife' }, { word: 'Streichholz', hint: 'Anzünden' }
    ],
  },
  {
    id: 'food',
    name: 'Essen & Trinken',
    icon: '🍕',
    hint: 'Essen',
    words: [
      { word: 'Pizza', hint: 'Ofen' }, { word: 'Spaghetti', hint: 'Italien' }, { word: 'Sushi', hint: 'Japan' }, { word: 'Burger', hint: 'Fastfood' }, { word: 'Schokolade', hint: 'Kakao' },
      { word: 'Käse', hint: 'Löcher' }, { word: 'Banane', hint: 'Krumm' }, { word: 'Kaffee', hint: 'Koffein' }, { word: 'Eis', hint: 'Schlecken' }, { word: 'Suppe', hint: 'Löffel' },
      { word: 'Salat', hint: 'Grün' }, { word: 'Pommes', hint: 'Frittiert' }, { word: 'Pfannkuchen', hint: 'Wenden' }, { word: 'Brezel', hint: 'Bayern' }, { word: 'Döner', hint: 'Spieß' },
      { word: 'Currywurst', hint: 'Imbiss' }, { word: 'Popcorn', hint: 'Kino' }, { word: 'Honig', hint: 'Bienen' }, { word: 'Erdbeere', hint: 'Sahne' }, { word: 'Zitrone', hint: 'Sauer' },
      { word: 'Reis', hint: 'Körner' }, { word: 'Nudeln', hint: 'Sieb' }, { word: 'Toast', hint: 'Frühstück' }, { word: 'Croissant', hint: 'Frankreich' }, { word: 'Waffel', hint: 'Puderzucker' },
      { word: 'Muffin', hint: 'Förmchen' }, { word: 'Steak', hint: 'Medium' }, { word: 'Lachs', hint: 'Rosa' }, { word: 'Kürbis', hint: 'Halloween' }, { word: 'Gurke', hint: 'Einlegen' },
      { word: 'Wassermelone', hint: 'Kerne' }, { word: 'Ananas', hint: 'Tropen' }, { word: 'Bier', hint: 'Schaumkrone' }, { word: 'Ketchup', hint: 'Tomaten' }, { word: 'Kuchen', hint: 'Geburtstag' },
      { word: 'Keks', hint: 'Krümel' }, { word: 'Brot', hint: 'Kruste' }, { word: 'Ei', hint: 'Schale' }, { word: 'Butter', hint: 'Streichen' }, { word: 'Marmelade', hint: 'Aufstrich' },
      { word: 'Joghurt', hint: 'Becher' }, { word: 'Müsli', hint: 'Haferflocken' }, { word: 'Pesto', hint: 'Basilikum' }, { word: 'Tacos', hint: 'Mexiko' }, { word: 'Ramen', hint: 'Brühe' },
      { word: 'Falafel', hint: 'Kichererbsen' }, { word: 'Tiramisu', hint: 'Dessert' }, { word: 'Gulasch', hint: 'Ungarn' }, { word: 'Schnitzel', hint: 'Panade' }, { word: 'Knoblauch', hint: 'Vampir' }
    ],
  },
  {
    id: 'animals',
    name: 'Tiere',
    icon: '🐾',
    hint: 'Tier',
    words: [
      { word: 'Elefant', hint: 'Savanne' }, { word: 'Löwe', hint: 'Mähne' }, { word: 'Pinguin', hint: 'Antarktis' }, { word: 'Delfin', hint: 'Sonar' }, { word: 'Adler', hint: 'Wappen' },
      { word: 'Krokodil', hint: 'Sumpf' }, { word: 'Giraffe', hint: 'Hals' }, { word: 'Känguru', hint: 'Beutel' }, { word: 'Igel', hint: 'Stacheln' }, { word: 'Fuchs', hint: 'Schlau' },
      { word: 'Wolf', hint: 'Rudel' }, { word: 'Bär', hint: 'Winterschlaf' }, { word: 'Hai', hint: 'Flosse' }, { word: 'Oktopus', hint: 'Tentakel' }, { word: 'Papagei', hint: 'Sprechen' },
      { word: 'Schildkröte', hint: 'Panzer' }, { word: 'Frosch', hint: 'Quaken' }, { word: 'Schlange', hint: 'Gift' }, { word: 'Biene', hint: 'Honig' }, { word: 'Schmetterling', hint: 'Raupe' },
      { word: 'Eule', hint: 'Nachtaktiv' }, { word: 'Zebra', hint: 'Streifen' }, { word: 'Nashorn', hint: 'Afrika' }, { word: 'Flamingo', hint: 'Rosa' }, { word: 'Waschbär', hint: 'Mülltonne' },
      { word: 'Faultier', hint: 'Langsam' }, { word: 'Panda', hint: 'Bambus' }, { word: 'Koala', hint: 'Eukalyptus' }, { word: 'Tiger', hint: 'Raubkatze' }, { word: 'Affe', hint: 'Klettern' },
      { word: 'Kamel', hint: 'Wüste' }, { word: 'Esel', hint: 'Stur' }, { word: 'Kuh', hint: 'Milch' }, { word: 'Pferd', hint: 'Galopp' }, { word: 'Maus', hint: 'Falle' },
      { word: 'Fledermaus', hint: 'Höhle' }, { word: 'Hase', hint: 'Möhren' }, { word: 'Katze', hint: 'Schnurren' }, { word: 'Wal', hint: 'Fontäne' }, { word: 'Robbe', hint: 'Eisscholle' },
      { word: 'Pfau', hint: 'Rad' }, { word: 'Strauß', hint: 'Sand' }, { word: 'Hamster', hint: 'Backen' }, { word: 'Chamäleon', hint: 'Farbwechsel' }, { word: 'Skorpion', hint: 'Sternzeichen' },
      { word: 'Qualle', hint: 'Glibber' }, { word: 'Ameise', hint: 'Krabbeln' }, { word: 'Libelle', hint: 'Teich' }, { word: 'Seepferdchen', hint: 'Schwimmkurs' }, { word: 'Murmeltier', hint: 'Alpen' }
    ],
  },
  {
    id: 'places',
    name: 'Orte',
    icon: '📍',
    hint: 'Ort',
    words: [
      { word: 'Strand', hint: 'Sandburg' }, { word: 'Flughafen', hint: 'Gate' }, { word: 'Krankenhaus', hint: 'Notaufnahme' }, { word: 'Schule', hint: 'Tafel' }, { word: 'Kino', hint: 'Leinwand' },
      { word: 'Bahnhof', hint: 'Gleis' }, { word: 'Supermarkt', hint: 'Einkaufswagen' }, { word: 'Bibliothek', hint: 'Leise' }, { word: 'Zoo', hint: 'Gehege' }, { word: 'Museum', hint: 'Ausstellung' },
      { word: 'Park', hint: 'Spaziergang' }, { word: 'Restaurant', hint: 'Kellner' }, { word: 'Schwimmbad', hint: 'Rutsche' }, { word: 'Fitnessstudio', hint: 'Hanteln' }, { word: 'Kirche', hint: 'Glocken' },
      { word: 'Schloss', hint: 'König' }, { word: 'Wüste', hint: 'Dünen' }, { word: 'Dschungel', hint: 'Lianen' }, { word: 'Vulkan', hint: 'Lava' }, { word: 'Insel', hint: 'Palmen' },
      { word: 'Höhle', hint: 'Tropfstein' }, { word: 'Leuchtturm', hint: 'Küste' }, { word: 'Hafen', hint: 'Anker' }, { word: 'Stadion', hint: 'Tribüne' }, { word: 'Zirkus', hint: 'Manege' },
      { word: 'Bäckerei', hint: 'Brötchen' }, { word: 'Tankstelle', hint: 'Zapfsäule' }, { word: 'Bauernhof', hint: 'Traktor' }, { word: 'Wald', hint: 'Pilze' }, { word: 'Hotel', hint: 'Rezeption' },
      { word: 'Aquarium', hint: 'Fische' }, { word: 'Bank', hint: 'Tresor' }, { word: 'Rathaus', hint: 'Bürgermeister' }, { word: 'Gefängnis', hint: 'Gitter' }, { word: 'Friseur', hint: 'Schere' },
      { word: 'Küche', hint: 'Herd' }, { word: 'Apotheke', hint: 'Medikamente' }, { word: 'Spielplatz', hint: 'Schaukel' }, { word: 'Baustelle', hint: 'Kran' }, { word: 'Friedhof', hint: 'Grabsteine' },
      { word: 'Jahrmarkt', hint: 'Karussell' }, { word: 'Sauna', hint: 'Aufguss' }, { word: 'Casino', hint: 'Roulette' }, { word: 'Theater', hint: 'Bühne' }, { word: 'Campingplatz', hint: 'Wohnwagen' },
      { word: 'Autobahn', hint: 'Stau' }, { word: 'Markt', hint: 'Stände' }, { word: 'Moschee', hint: 'Minarett' }, { word: 'Universität', hint: 'Vorlesung' }, { word: 'Polizeiwache', hint: 'Verhör' }
    ],
  },
  {
    id: 'jobs',
    name: 'Berufe',
    icon: '💼',
    hint: 'Beruf',
    words: [
      { word: 'Arzt', hint: 'Kittel' }, { word: 'Lehrer', hint: 'Kreide' }, { word: 'Polizist', hint: 'Blaulicht' }, { word: 'Feuerwehrmann', hint: 'Schlauch' }, { word: 'Koch', hint: 'Töpfe' },
      { word: 'Pilot', hint: 'Cockpit' }, { word: 'Bäcker', hint: 'Teig' }, { word: 'Friseur', hint: 'Kamm' }, { word: 'Anwalt', hint: 'Paragraf' }, { word: 'Richter', hint: 'Urteil' },
      { word: 'Astronaut', hint: 'Schwerelos' }, { word: 'Bauer', hint: 'Ernte' }, { word: 'Elektriker', hint: 'Kabel' }, { word: 'Klempner', hint: 'Rohre' }, { word: 'Zahnarzt', hint: 'Bohrer' },
      { word: 'Krankenpfleger', hint: 'Spritze' }, { word: 'Programmierer', hint: 'Code' }, { word: 'Ingenieur', hint: 'Berechnung' }, { word: 'Architekt', hint: 'Bauplan' }, { word: 'Maler', hint: 'Pinsel' },
      { word: 'Musiker', hint: 'Instrument' }, { word: 'Schauspieler', hint: 'Drehbuch' }, { word: 'Kellner', hint: 'Trinkgeld' }, { word: 'Metzger', hint: 'Fleisch' }, { word: 'Gärtner', hint: 'Beet' },
      { word: 'Mechaniker', hint: 'Schraubenschlüssel' }, { word: 'Fotograf', hint: 'Blitz' }, { word: 'Journalist', hint: 'Interview' }, { word: 'Detektiv', hint: 'Lupe' }, { word: 'Soldat', hint: 'Kaserne' },
      { word: 'Fischer', hint: 'Netz' }, { word: 'Bibliothekar', hint: 'Ausleihe' }, { word: 'DJ', hint: 'Auflegen' }, { word: 'Tierarzt', hint: 'Haustiere' }, { word: 'Postbote', hint: 'Briefkasten' },
      { word: 'Barkeeper', hint: 'Shaker' }, { word: 'Pfarrer', hint: 'Predigt' }, { word: 'Schreiner', hint: 'Holz' }, { word: 'Dachdecker', hint: 'Ziegel' }, { word: 'Schornsteinfeger', hint: 'Glück' },
      { word: 'Taxifahrer', hint: 'Taxameter' }, { word: 'Kapitän', hint: 'Steuerrad' }, { word: 'Model', hint: 'Laufsteg' }, { word: 'Politiker', hint: 'Wahlkampf' }, { word: 'Wissenschaftler', hint: 'Labor' },
      { word: 'Psychologe', hint: 'Couch' }, { word: 'Optiker', hint: 'Sehtest' }, { word: 'Förster', hint: 'Revier' }, { word: 'Winzer', hint: 'Trauben' }, { word: 'Chirurg', hint: 'Skalpell' }
    ],
  },
  {
    id: 'movies',
    name: 'Filme & Serien',
    icon: '🎬',
    hint: 'Film/Serie',
    words: [
      { word: 'Titanic', hint: 'Eisberg' }, { word: 'Avatar', hint: 'Blau' }, { word: 'Batman', hint: 'Umhang' }, { word: 'Spider-Man', hint: 'Marvel' }, { word: 'Harry Potter', hint: 'Zauberstab' },
      { word: 'Star Wars', hint: 'Laserschwert' }, { word: 'Herr der Ringe', hint: 'Elben' }, { word: 'Matrix', hint: 'Pillen' }, { word: 'Frozen', hint: 'Schneemann' }, { word: 'Shrek', hint: 'Sumpf' },
      { word: 'Findet Nemo', hint: 'Vergesslich' }, { word: 'König der Löwen', hint: 'Savanne' }, { word: 'Jurassic Park', hint: 'Bernstein' }, { word: 'Fluch der Karibik', hint: 'Kompass' }, { word: 'Fast & Furious', hint: 'Tuning' },
      { word: 'James Bond', hint: 'Martini' }, { word: 'Joker', hint: 'Lachen' }, { word: 'Barbie', hint: 'Pink' }, { word: 'Oppenheimer', hint: 'Manhattan' }, { word: 'Inception', hint: 'Träume' },
      { word: 'Gladiator', hint: 'Arena' }, { word: 'Breaking Bad', hint: 'Wohnmobil' }, { word: 'Game of Thrones', hint: 'Drachen' }, { word: 'Stranger Things', hint: 'Achtziger' }, { word: 'The Office', hint: 'Papier' },
      { word: 'Friends', hint: 'WG' }, { word: 'Haus des Geldes', hint: 'Maske' }, { word: 'Wednesday', hint: 'Internat' }, { word: 'Dark', hint: 'Zeitreise' }, { word: 'Squid Game', hint: 'Korea' },
      { word: 'Minions', hint: 'Gelb' }, { word: 'Toy Story', hint: 'Cowboy' }, { word: 'Cars', hint: 'Reifen' }, { word: 'Deadpool', hint: 'Antiheld' }, { word: 'Interstellar', hint: 'Wurmloch' },
      { word: 'Avengers', hint: 'Superhelden' }, { word: 'Fight Club', hint: 'Regeln' }, { word: 'Forrest Gump', hint: 'Pralinen' }, { word: 'Der Pate', hint: 'Mafia' }, { word: 'Hangover', hint: 'Vegas' },
      { word: 'E.T.', hint: 'Telefon' }, { word: 'Ratatouille', hint: 'Paris' }, { word: 'Spongebob', hint: 'Ananas' }, { word: 'Die Simpsons', hint: 'Donuts' }, { word: 'How I Met Your Mother', hint: 'Legendär' },
      { word: 'Prison Break', hint: 'Tattoo' }, { word: 'Sherlock', hint: 'London' }, { word: 'Peaky Blinders', hint: 'Schiebermütze' }, { word: 'Dune', hint: 'Gewürz' }, { word: 'Zurück in die Zukunft', hint: 'DeLorean' }
    ],
  },
  {
    id: 'stars',
    name: 'Promis',
    icon: '🌟',
    hint: 'Person',
    words: [
      { word: 'Cristiano Ronaldo', hint: 'Portugal' }, { word: 'Lionel Messi', hint: 'Argentinien' }, { word: 'Taylor Swift', hint: 'Eras' }, { word: 'Beyoncé', hint: 'Queen' }, { word: 'Drake', hint: 'Toronto' },
      { word: 'Rihanna', hint: 'Barbados' }, { word: 'Adele', hint: 'Balladen' }, { word: 'Ed Sheeran', hint: 'Rothaarig' }, { word: 'Eminem', hint: 'Detroit' }, { word: 'Elon Musk', hint: 'Raketen' },
      { word: 'Bill Gates', hint: 'Windows' }, { word: 'Barack Obama', hint: 'Präsident' }, { word: 'Albert Einstein', hint: 'Zunge' }, { word: 'Michael Jackson', hint: 'Moonwalk' }, { word: 'Elvis Presley', hint: 'Hüftschwung' },
      { word: 'Lady Gaga', hint: 'Fleischkleid' }, { word: 'Billie Eilish', hint: 'Flüstern' }, { word: 'Kanye West', hint: 'Ego' }, { word: 'Kim Kardashian', hint: 'Reality' }, { word: 'Shakira', hint: 'Kolumbien' },
      { word: 'Neymar', hint: 'Brasilien' }, { word: 'LeBron James', hint: 'Basketball' }, { word: 'Dwayne Johnson', hint: 'Wrestler' }, { word: 'Leonardo DiCaprio', hint: 'Oscar' }, { word: 'Brad Pitt', hint: 'Hollywood' },
      { word: 'Angelina Jolie', hint: 'Tattoos' }, { word: 'Mr Beast', hint: 'Challenges' }, { word: 'Ariana Grande', hint: 'Pferdeschwanz' }, { word: 'Justin Bieber', hint: 'Baby' }, { word: 'Snoop Dogg', hint: 'Westcoast' },
      { word: 'Bruno Mars', hint: 'Funk' }, { word: 'Zendaya', hint: 'Euphoria' }, { word: 'Michael Schumacher', hint: 'Rennfahrer' }, { word: 'Manuel Neuer', hint: 'Torwart' }, { word: 'Toni Kroos', hint: 'Mittelfeld' },
      { word: 'Helene Fischer', hint: 'Atemlos' }, { word: 'Capital Bra', hint: 'Deutschrap' }, { word: 'Apache 207', hint: 'Sonnenbrille' }, { word: 'Dieter Bohlen', hint: 'Casting' }, { word: 'Heidi Klum', hint: 'Topmodel' },
      { word: 'Angela Merkel', hint: 'Raute' }, { word: 'Arnold Schwarzenegger', hint: 'Österreich' }, { word: 'Lewis Hamilton', hint: 'Mercedes' }, { word: 'Roger Federer', hint: 'Tennis' }, { word: 'Usain Bolt', hint: 'Sprint' },
      { word: 'Rezo', hint: 'Zerstörung' }, { word: 'Knossi', hint: 'Twitch' }, { word: 'MontanaBlack', hint: 'Streamer' }, { word: 'Olaf Scholz', hint: 'Kanzler' }, { word: 'Robert Lewandowski', hint: 'Torjäger' }
    ],
  },
  {
    id: 'brands',
    name: 'Marken',
    icon: '🏷️',
    hint: 'Marke',
    words: [
      { word: 'Coca-Cola', hint: 'Brause' }, { word: 'Pepsi', hint: 'Blau' }, { word: 'Nike', hint: 'Haken' }, { word: 'Adidas', hint: 'Streifen' }, { word: 'Apple', hint: 'Angebissen' },
      { word: 'Samsung', hint: 'Korea' }, { word: 'Google', hint: 'Suchmaschine' }, { word: 'Amazon', hint: 'Pakete' }, { word: 'Netflix', hint: 'Serien' }, { word: 'McDonald’s', hint: 'Clown' },
      { word: 'Burger King', hint: 'Krone' }, { word: 'Starbucks', hint: 'Kaffeekette' }, { word: 'Ikea', hint: 'Schweden' }, { word: 'Lego', hint: 'Bausteine' }, { word: 'Ferrari', hint: 'Pferd' },
      { word: 'Lamborghini', hint: 'Stier' }, { word: 'BMW', hint: 'München' }, { word: 'Mercedes', hint: 'Stern' }, { word: 'Tesla', hint: 'Elektro' }, { word: 'Porsche', hint: 'Stuttgart' },
      { word: 'Rolex', hint: 'Handgelenk' }, { word: 'Gucci', hint: 'Italien' }, { word: 'Louis Vuitton', hint: 'Handtaschen' }, { word: 'Chanel', hint: 'Parfüm' }, { word: 'Red Bull', hint: 'Flügel' },
      { word: 'Nutella', hint: 'Haselnuss' }, { word: 'Lindt', hint: 'Goldhase' }, { word: 'Spotify', hint: 'Streaming' }, { word: 'YouTube', hint: 'Videos' }, { word: 'Instagram', hint: 'Filter' },
      { word: 'TikTok', hint: 'Tänze' }, { word: 'PlayStation', hint: 'Konsole' }, { word: 'Xbox', hint: 'Microsoft' }, { word: 'Nintendo', hint: 'Mario' }, { word: 'Haribo', hint: 'Gummibärchen' },
      { word: 'Milka', hint: 'Lila' }, { word: 'Ritter Sport', hint: 'Quadratisch' }, { word: 'Volkswagen', hint: 'Käfer' }, { word: 'Audi', hint: 'Ringe' }, { word: 'Aldi', hint: 'Discounter' },
      { word: 'Lidl', hint: 'Discounter' }, { word: 'Zalando', hint: 'Mode' }, { word: 'Snapchat', hint: 'Geist' }, { word: 'WhatsApp', hint: 'Chatten' }, { word: 'Disney', hint: 'Micky' },
      { word: 'Shell', hint: 'Muschel' }, { word: 'Lufthansa', hint: 'Kranich' }, { word: 'Deutsche Bahn', hint: 'Verspätung' }, { word: 'Fanta', hint: 'Orange' }, { word: 'Oreo', hint: 'Schwarzweiß' }
    ],
  },
  {
    id: 'sport',
    name: 'Sport',
    icon: '⚽',
    hint: 'Sport',
    words: [
      { word: 'Fußball', hint: 'Elfmeter' }, { word: 'Basketball', hint: 'Korb' }, { word: 'Tennis', hint: 'Aufschlag' }, { word: 'Golf', hint: 'Abschlag' }, { word: 'Boxen', hint: 'Ring' },
      { word: 'Schwimmen', hint: 'Bahnen' }, { word: 'Skifahren', hint: 'Piste' }, { word: 'Snowboarden', hint: 'Halfpipe' }, { word: 'Surfen', hint: 'Welle' }, { word: 'Klettern', hint: 'Wand' },
      { word: 'Reiten', hint: 'Sattel' }, { word: 'Turnen', hint: 'Barren' }, { word: 'Volleyball', hint: 'Baggern' }, { word: 'Handball', hint: 'Harz' }, { word: 'Eishockey', hint: 'Puck' },
      { word: 'Baseball', hint: 'Homerun' }, { word: 'Rugby', hint: 'Ei' }, { word: 'Cricket', hint: 'England' }, { word: 'Bogenschießen', hint: 'Pfeil' }, { word: 'Fechten', hint: 'Degen' },
      { word: 'Judo', hint: 'Gürtel' }, { word: 'Karate', hint: 'Bretter' }, { word: 'Ringen', hint: 'Matte' }, { word: 'Marathon', hint: 'Ausdauer' }, { word: 'Radfahren', hint: 'Tour' },
      { word: 'Rudern', hint: 'Boot' }, { word: 'Segeln', hint: 'Wind' }, { word: 'Tauchen', hint: 'Sauerstoff' }, { word: 'Darts', hint: 'Kneipe' }, { word: 'Billard', hint: 'Queue' },
      { word: 'Bowling', hint: 'Strike' }, { word: 'Tischtennis', hint: 'Kelle' }, { word: 'Skateboarden', hint: 'Rampe' }, { word: 'Yoga', hint: 'Dehnen' }, { word: 'Leichtathletik', hint: 'Hürden' },
      { word: 'Formel 1', hint: 'Boxenstopp' }, { word: 'Biathlon', hint: 'Gewehr' }, { word: 'Eiskunstlauf', hint: 'Pirouette' }, { word: 'Kegeln', hint: 'Neune' }, { word: 'Badminton', hint: 'Feder' },
      { word: 'Squash', hint: 'Gummiball' }, { word: 'Triathlon', hint: 'Wechselzone' }, { word: 'Gewichtheben', hint: 'Stemmen' }, { word: 'Zumba', hint: 'Fitnesskurs' }, { word: 'Schach', hint: 'Matt' },
      { word: 'Angeln', hint: 'Köder' }, { word: 'Parkour', hint: 'Hindernisse' }, { word: 'Wandern', hint: 'Alpen' }, { word: 'Curling', hint: 'Wischen' }, { word: 'Sumo', hint: 'Japan' }
    ],
  },
  {
    id: 'countries',
    name: 'Länder & Städte',
    icon: '🌍',
    hint: 'Ort',
    words: [
      { word: 'Deutschland', hint: 'Pünktlichkeit' }, { word: 'Frankreich', hint: 'Baguette' }, { word: 'Italien', hint: 'Pasta' }, { word: 'Spanien', hint: 'Siesta' }, { word: 'England', hint: 'Tee' },
      { word: 'USA', hint: 'Dollar' }, { word: 'Japan', hint: 'Kirschblüten' }, { word: 'China', hint: 'Mauer' }, { word: 'Brasilien', hint: 'Samba' }, { word: 'Australien', hint: 'Outback' },
      { word: 'Kanada', hint: 'Ahorn' }, { word: 'Mexiko', hint: 'Sombrero' }, { word: 'Ägypten', hint: 'Pyramiden' }, { word: 'Indien', hint: 'Bollywood' }, { word: 'Russland', hint: 'Kreml' },
      { word: 'Griechenland', hint: 'Antike' }, { word: 'Türkei', hint: 'Basar' }, { word: 'Norwegen', hint: 'Fjorde' }, { word: 'Berlin', hint: 'Hauptstadt' }, { word: 'Paris', hint: 'Mode' },
      { word: 'London', hint: 'Nebel' }, { word: 'New York', hint: 'Wolkenkratzer' }, { word: 'Tokio', hint: 'Anime' }, { word: 'Rom', hint: 'Papst' }, { word: 'Madrid', hint: 'Real' },
      { word: 'Dubai', hint: 'Scheichs' }, { word: 'Amsterdam', hint: 'Grachten' }, { word: 'Barcelona', hint: 'Tapas' }, { word: 'Istanbul', hint: 'Bosporus' }, { word: 'Sydney', hint: 'Oper' },
      { word: 'Las Vegas', hint: 'Jackpot' }, { word: 'Wien', hint: 'Schnitzel' }, { word: 'Zürich', hint: 'Banken' }, { word: 'Rio de Janeiro', hint: 'Zuckerhut' }, { word: 'Portugal', hint: 'Kork' },
      { word: 'Niederlande', hint: 'Tulpen' }, { word: 'Schweiz', hint: 'Neutralität' }, { word: 'Österreich', hint: 'Mozartkugeln' }, { word: 'Polen', hint: 'Pierogi' }, { word: 'Schweden', hint: 'Elche' },
      { word: 'Island', hint: 'Geysire' }, { word: 'Thailand', hint: 'Backpacker' }, { word: 'Marokko', hint: 'Couscous' }, { word: 'Argentinien', hint: 'Tango' }, { word: 'Hawaii', hint: 'Aloha' },
      { word: 'Grönland', hint: 'Gletscher' }, { word: 'Hamburg', hint: 'Fischbrötchen' }, { word: 'München', hint: 'Oktoberfest' }, { word: 'Köln', hint: 'Dom' }, { word: 'Venedig', hint: 'Gondeln' }
    ],
  },
  {
    id: 'body',
    name: 'Körperteile',
    icon: '🫀',
    hint: 'Körper',
    words: [
      { word: 'Kopf', hint: 'Oben' }, { word: 'Auge', hint: 'Blinzeln' }, { word: 'Nase', hint: 'Riechen' }, { word: 'Mund', hint: 'Lippen' }, { word: 'Ohr', hint: 'Lauschen' },
      { word: 'Zunge', hint: 'Schmecken' }, { word: 'Zahn', hint: 'Beißen' }, { word: 'Haar', hint: 'Frisur' }, { word: 'Hals', hint: 'Schal' }, { word: 'Schulter', hint: 'Zucken' },
      { word: 'Arm', hint: 'Winken' }, { word: 'Ellbogen', hint: 'Gelenk' }, { word: 'Hand', hint: 'Greifen' }, { word: 'Finger', hint: 'Zeigen' }, { word: 'Daumen', hint: 'Hoch' },
      { word: 'Bauch', hint: 'Grummeln' }, { word: 'Rücken', hint: 'Schmerzen' }, { word: 'Bein', hint: 'Laufen' }, { word: 'Knie', hint: 'Beugen' }, { word: 'Fuß', hint: 'Socken' },
      { word: 'Zeh', hint: 'Stoßen' }, { word: 'Ferse', hint: 'Achilles' }, { word: 'Herz', hint: 'Brustkorb' }, { word: 'Gehirn', hint: 'Denken' }, { word: 'Lunge', hint: 'Atmen' },
      { word: 'Magen', hint: 'Knurren' }, { word: 'Leber', hint: 'Entgiftung' }, { word: 'Rippe', hint: 'Adam' }, { word: 'Wirbelsäule', hint: 'Aufrecht' }, { word: 'Kinn', hint: 'Bart' },
      { word: 'Wange', hint: 'Erröten' }, { word: 'Augenbraue', hint: 'Zupfen' }, { word: 'Wimper', hint: 'Tusche' }, { word: 'Nabel', hint: 'Mitte' }, { word: 'Stirn', hint: 'Falten' },
      { word: 'Nacken', hint: 'Verspannt' }, { word: 'Handgelenk', hint: 'Uhr' }, { word: 'Knöchel', hint: 'Umknicken' }, { word: 'Wade', hint: 'Krampf' }, { word: 'Oberschenkel', hint: 'Squats' },
      { word: 'Po', hint: 'Polster' }, { word: 'Hüfte', hint: 'Schwung' }, { word: 'Niere', hint: 'Bohne' }, { word: 'Blase', hint: 'Toilette' }, { word: 'Muskel', hint: 'Training' },
      { word: 'Knochen', hint: 'Skelett' }, { word: 'Haut', hint: 'Sonnenbrand' }, { word: 'Blut', hint: 'Spende' }, { word: 'Nerven', hint: 'Signale' }, { word: 'Zwerchfell', hint: 'Schluckauf' }
    ],
  },
  {
    id: 'household',
    name: 'Haushalt',
    icon: '🏠',
    hint: 'Gegenstand',
    words: [
      { word: 'Kühlschrank', hint: 'Kalt' }, { word: 'Waschmaschine', hint: 'Schleudern' }, { word: 'Staubsauger', hint: 'Beutel' }, { word: 'Mikrowelle', hint: 'Aufwärmen' }, { word: 'Toaster', hint: 'Schlitze' },
      { word: 'Herd', hint: 'Platten' }, { word: 'Backofen', hint: 'Vorheizen' }, { word: 'Wasserkocher', hint: 'Tee' }, { word: 'Bügeleisen', hint: 'Dampf' }, { word: 'Föhn', hint: 'Trocknen' },
      { word: 'Fernseher', hint: 'Programm' }, { word: 'Sofa', hint: 'Lümmeln' }, { word: 'Bett', hint: 'Matratze' }, { word: 'Schrank', hint: 'Kleiderbügel' }, { word: 'Tisch', hint: 'Esszimmer' },
      { word: 'Stuhl', hint: 'Lehne' }, { word: 'Teppich', hint: 'Fransen' }, { word: 'Vorhang', hint: 'Zuziehen' }, { word: 'Spülmaschine', hint: 'Tabs' }, { word: 'Besen', hint: 'Fegen' },
      { word: 'Eimer', hint: 'Putzwasser' }, { word: 'Schwamm', hint: 'Abwasch' }, { word: 'Handtuch', hint: 'Frottee' }, { word: 'Kissen', hint: 'Federn' }, { word: 'Decke', hint: 'Kuscheln' },
      { word: 'Wecker', hint: 'Snooze' }, { word: 'Kerze', hint: 'Docht' }, { word: 'Bilderrahmen', hint: 'Aufhängen' }, { word: 'Blumentopf', hint: 'Erde' }, { word: 'Mülleimer', hint: 'Gestank' },
      { word: 'Steckdose', hint: 'Strom' }, { word: 'Türklinke', hint: 'Drücken' }, { word: 'Klopapier', hint: 'Rolle' }, { word: 'Waschbecken', hint: 'Abfluss' }, { word: 'Dusche', hint: 'Warmwasser' },
      { word: 'Badewanne', hint: 'Schaumbad' }, { word: 'Heizung', hint: 'Thermostat' }, { word: 'Regal', hint: 'Fächer' }, { word: 'Nachttisch', hint: 'Schublade' }, { word: 'Gießkanne', hint: 'Balkon' },
      { word: 'Wäscheständer', hint: 'Klammern' }, { word: 'Gefriertruhe', hint: 'Frost' }, { word: 'Kaffeemaschine', hint: 'Filter' }, { word: 'Mixer', hint: 'Smoothie' }, { word: 'Pfanne', hint: 'Braten' },
      { word: 'Topf', hint: 'Deckel' }, { word: 'Schneidebrett', hint: 'Gemüse' }, { word: 'Korkenzieher', hint: 'Wein' }, { word: 'Dosenöffner', hint: 'Konserven' }, { word: 'Rasenmäher', hint: 'Garten' }
    ],
  },
  {
    id: 'school',
    name: 'Schule',
    icon: '🎒',
    hint: 'Schule',
    words: [
      { word: 'Tafel', hint: 'Schwamm' }, { word: 'Kreide', hint: 'Staub' }, { word: 'Heft', hint: 'Linien' }, { word: 'Stift', hint: 'Mine' }, { word: 'Radiergummi', hint: 'Fehler' },
      { word: 'Lineal', hint: 'Zentimeter' }, { word: 'Schere', hint: 'Schneiden' }, { word: 'Kleber', hint: 'Basteln' }, { word: 'Rucksack', hint: 'Schleppen' }, { word: 'Pausenbrot', hint: 'Dose' },
      { word: 'Klassenzimmer', hint: 'Sitzplan' }, { word: 'Lehrer', hint: 'Pult' }, { word: 'Hausaufgabe', hint: 'Vergessen' }, { word: 'Prüfung', hint: 'Schwitzen' }, { word: 'Zeugnis', hint: 'Versetzung' },
      { word: 'Note', hint: 'Sechs' }, { word: 'Mathe', hint: 'Zahlen' }, { word: 'Deutsch', hint: 'Diktat' }, { word: 'Englisch', hint: 'Vokabeln' }, { word: 'Chemie', hint: 'Experimente' },
      { word: 'Biologie', hint: 'Zellen' }, { word: 'Physik', hint: 'Formeln' }, { word: 'Geschichte', hint: 'Vergangenheit' }, { word: 'Sportunterricht', hint: 'Umkleide' }, { word: 'Pause', hint: 'Klingel' },
      { word: 'Schulhof', hint: 'Toben' }, { word: 'Bibliothek', hint: 'Regale' }, { word: 'Turnhalle', hint: 'Sprossenwand' }, { word: 'Mensa', hint: 'Tablett' }, { word: 'Direktor', hint: 'Anzug' },
      { word: 'Spickzettel', hint: 'Schummeln' }, { word: 'Taschenrechner', hint: 'Tasten' }, { word: 'Globus', hint: 'Drehen' }, { word: 'Federmäppchen', hint: 'Reißverschluss' }, { word: 'Klassenfahrt', hint: 'Jugendherberge' },
      { word: 'Stundenplan', hint: 'Fächer' }, { word: 'Melden', hint: 'Handzeichen' }, { word: 'Nachsitzen', hint: 'Strafe' }, { word: 'Abschlussball', hint: 'Kleid' }, { word: 'Referat', hint: 'PowerPoint' },
      { word: 'Abitur', hint: 'Abschluss' }, { word: 'Hitzefrei', hint: 'Sommer' }, { word: 'Streber', hint: 'Einser' }, { word: 'Banknachbar', hint: 'Abschreiben' }, { word: 'Kunst', hint: 'Malkasten' },
      { word: 'Elternabend', hint: 'Peinlich' }, { word: 'Vertretungsstunde', hint: 'Ausfall' }, { word: 'Schulbus', hint: 'Haltestelle' }, { word: 'Zirkel', hint: 'Kreise' }, { word: 'Füller', hint: 'Tinte' }
    ],
  },
  {
    id: 'tech',
    name: 'Technik',
    icon: '📱',
    hint: 'Technik',
    words: [
      { word: 'Smartphone', hint: 'Selfies' }, { word: 'Laptop', hint: 'Klappen' }, { word: 'Tablet', hint: 'Flach' }, { word: 'Kopfhörer', hint: 'Stöpsel' }, { word: 'Kamera', hint: 'Objektiv' },
      { word: 'Drohne', hint: 'Propeller' }, { word: 'Roboter', hint: 'Metall' }, { word: 'Ladekabel', hint: 'Steckdose' }, { word: 'Powerbank', hint: 'Unterwegs' }, { word: 'Router', hint: 'Blinken' },
      { word: 'Bluetooth', hint: 'Verbinden' }, { word: 'WLAN', hint: 'Empfang' }, { word: 'USB-Stick', hint: 'Anschluss' }, { word: 'Festplatte', hint: 'Speicher' }, { word: 'Grafikkarte', hint: 'Gaming' },
      { word: 'Prozessor', hint: 'Chip' }, { word: 'Bildschirm', hint: 'Pixel' }, { word: 'Tastatur', hint: 'Tippen' }, { word: 'Maus', hint: 'Klicken' }, { word: 'Drucker', hint: 'Papierstau' },
      { word: 'Scanner', hint: 'Einlesen' }, { word: 'Smartwatch', hint: 'Schritte' }, { word: 'VR-Brille', hint: 'Eintauchen' }, { word: 'Konsole', hint: 'Zocken' }, { word: 'Controller', hint: 'Vibration' },
      { word: 'Beamer', hint: 'Leinwand' }, { word: 'Lautsprecher', hint: 'Bass' }, { word: 'Mikrofon', hint: 'Aufnahme' }, { word: 'GPS', hint: 'Satelliten' }, { word: 'Akku', hint: 'Prozent' },
      { word: 'App', hint: 'Herunterladen' }, { word: 'Passwort', hint: 'Sternchen' }, { word: 'Cloud', hint: 'Hochladen' }, { word: 'Emoji', hint: 'Chats' }, { word: 'Algorithmus', hint: 'Empfehlungen' },
      { word: 'KI', hint: 'ChatGPT' }, { word: 'Virus', hint: 'Infiziert' }, { word: 'Update', hint: 'Neustart' }, { word: 'Browser', hint: 'Tabs' }, { word: 'E-Mail', hint: 'Posteingang' },
      { word: 'Bitcoin', hint: 'Mining' }, { word: 'Webcam', hint: 'Meetings' }, { word: 'Server', hint: 'Rechenzentrum' }, { word: 'Touchscreen', hint: 'Fingerabdrücke' }, { word: 'Hologramm', hint: 'Science-Fiction' },
      { word: 'Joystick', hint: 'Arcade' }, { word: 'E-Scooter', hint: 'Gehweg' }, { word: '3D-Drucker', hint: 'Schichten' }, { word: 'Antenne', hint: 'Dach' }, { word: 'Screenshot', hint: 'Festhalten' }
    ],
  },
  {
    id: 'funny',
    name: 'Quatsch & Lustig',
    icon: '🤪',
    hint: 'Quatsch',
    words: [
      { word: 'Furz', hint: 'Bohnen' }, { word: 'Nasenpopel', hint: 'Bohren' }, { word: 'Unterhose', hint: 'Drunter' }, { word: 'Schnurrbart', hint: 'Zwirbeln' }, { word: 'Gummiente', hint: 'Quietschen' },
      { word: 'Clown', hint: 'Nase' }, { word: 'Einhorn', hint: 'Regenbogen' }, { word: 'Zwerg', hint: 'Klein' }, { word: 'Zombie', hint: 'Untot' }, { word: 'Alien', hint: 'UFO' },
      { word: 'Nacktschnecke', hint: 'Schleim' }, { word: 'Schnabeltier', hint: 'Australien' }, { word: 'Toilette', hint: 'Spülung' }, { word: 'Windel', hint: 'Baby' }, { word: 'Zahnspange', hint: 'Draht' },
      { word: 'Perücke', hint: 'Aufsetzen' }, { word: 'Glatze', hint: 'Polieren' }, { word: 'Doppelkinn', hint: 'Selfiewinkel' }, { word: 'Schluckauf', hint: 'Erschrecken' }, { word: 'Niesen', hint: 'Gesundheit' },
      { word: 'Kitzeln', hint: 'Lachen' }, { word: 'Pupsen', hint: 'Leugnen' }, { word: 'Grimasse', hint: 'Verziehen' }, { word: 'Selfie', hint: 'Duckface' }, { word: 'Verstopfung', hint: 'Pflaumen' },
      { word: 'Ohrwurm', hint: 'Dauerschleife' }, { word: 'Fettnäpfchen', hint: 'Reintreten' }, { word: 'Warze', hint: 'Frosch' }, { word: 'Schweißfleck', hint: 'Vorstellungsgespräch' }, { word: 'Achselhaar', hint: 'Rasieren' },
      { word: 'Sabber', hint: 'Mittagsschlaf' }, { word: 'Rülpsen', hint: 'Limo' }, { word: 'Bauchnabelfussel', hint: 'Flusen' }, { word: 'Kuscheltier', hint: 'Teddy' }, { word: 'Stinkefinger', hint: 'Beleidigung' },
      { word: 'Klobrille', hint: 'Hochklappen' }, { word: 'Furzkissen', hint: 'Scherzartikel' }, { word: 'Pickel', hint: 'Ausdrücken' }, { word: 'Mundgeruch', hint: 'Kaugummi' }, { word: 'Schnarchen', hint: 'Nachts' },
      { word: 'Stolpern', hint: 'Bordstein' }, { word: 'Bananenschale', hint: 'Ausrutschen' }, { word: 'Juckreiz', hint: 'Kratzen' }, { word: 'Käsefüße', hint: 'Turnschuhe' }, { word: 'Milchbart', hint: 'Oberlippe' },
      { word: 'Wackelzahn', hint: 'Ziehen' }, { word: 'Lachanfall', hint: 'Unpassend' }, { word: 'Gähnen', hint: 'Ansteckend' }, { word: 'Nasenhaar', hint: 'Pinzette' }, { word: 'Kichern', hint: 'Unterricht' }
    ],
  },
  {
    id: 'party',
    name: 'Party',
    icon: '🎉',
    hint: 'Party',
    words: [
      { word: 'Bier', hint: 'Zapfhahn' }, { word: 'Cocktail', hint: 'Schirmchen' }, { word: 'Shot', hint: 'Exen' }, { word: 'Tequila', hint: 'Salz' }, { word: 'Wodka', hint: 'Russland' },
      { word: 'Sekt', hint: 'Korken' }, { word: 'Bierpong', hint: 'Becher' }, { word: 'Tanzfläche', hint: 'Parkett' }, { word: 'DJ', hint: 'Wünsche' }, { word: 'Discokugel', hint: 'Glitzern' },
      { word: 'Karaoke', hint: 'Mitsingen' }, { word: 'Konfetti', hint: 'Schnipsel' }, { word: 'Luftballon', hint: 'Platzen' }, { word: 'Geburtstag', hint: 'Ständchen' }, { word: 'Torte', hint: 'Etagen' },
      { word: 'Feuerwerk', hint: 'Raketen' }, { word: 'Trinkspiel', hint: 'Karten' }, { word: 'Kater', hint: 'Morgen' }, { word: 'Absturz', hint: 'Filmriss' }, { word: 'Nachtclub', hint: 'Warteschlange' },
      { word: 'Türsteher', hint: 'Ausweis' }, { word: 'Wackelpudding', hint: 'Wabbelig' }, { word: 'Flunkyball', hint: 'Umkippen' }, { word: 'Kostüm', hint: 'Verkleiden' }, { word: 'Junggesellenabschied', hint: 'Bräutigam' },
      { word: 'Silvester', hint: 'Countdown' }, { word: 'Festival', hint: 'Bändchen' }, { word: 'Lagerfeuer', hint: 'Stockbrot' }, { word: 'Grillen', hint: 'Kohle' }, { word: 'Wunderkerze', hint: 'Funkeln' },
      { word: 'Anstoßen', hint: 'Prost' }, { word: 'Tanzen', hint: 'Rhythmus' }, { word: 'Betrunken', hint: 'Lallen' }, { word: 'Afterparty', hint: 'Sonnenaufgang' }, { word: 'Bowle', hint: 'Früchte' },
      { word: 'Jägermeister', hint: 'Kräuter' }, { word: 'Aperol', hint: 'Bitter' }, { word: 'Limbo', hint: 'Stange' }, { word: 'Polonaise', hint: 'Reihe' }, { word: 'Einladung', hint: 'Gästeliste' },
      { word: 'Luftschlangen', hint: 'Pusten' }, { word: 'Piñata', hint: 'Süßigkeiten' }, { word: 'Flaschendrehen', hint: 'Küssen' }, { word: 'Mottoparty', hint: 'Thema' }, { word: 'Katerfrühstück', hint: 'Aspirin' },
      { word: 'Garderobe', hint: 'Jacken' }, { word: 'Barhocker', hint: 'Tresen' }, { word: 'Vorglühen', hint: 'Sparen' }, { word: 'Heimweg', hint: 'Döner' }, { word: 'Sektdusche', hint: 'Podium' }
    ],
  },
  {
    id: 'adult',
    name: '18+ Anzüglich',
    icon: '🔞',
    hint: '18+',
    adult: true,
    words: [
      { word: 'Kondom', hint: 'Gummi' }, { word: 'Dessous', hint: 'Spitze' }, { word: 'Tanga', hint: 'Knapp' }, { word: 'Höschen', hint: 'Seide' }, { word: 'Reizwäsche', hint: 'Anlass' },
      { word: 'Nachthemd', hint: 'Schlafzimmer' }, { word: 'Kussmund', hint: 'Lippenstift' }, { word: 'Knutschfleck', hint: 'Rollkragen' }, { word: 'Zungenkuss', hint: 'Französisch' }, { word: 'Flirt', hint: 'Zwinkern' },
      { word: 'One-Night-Stand', hint: 'Aufwachen' }, { word: 'Tinder', hint: 'Wischen' }, { word: 'Blind Date', hint: 'Überraschung' }, { word: 'Verführung', hint: 'Blicke' }, { word: 'Techtelmechtel', hint: 'Heimlich' },
      { word: 'Vorspiel', hint: 'Aufwärmen' }, { word: 'Rotlichtviertel', hint: 'Amsterdam' }, { word: 'Stripclub', hint: 'Scheine' }, { word: 'Poledance', hint: 'Stange' }, { word: 'Handschellen', hint: 'Bettpfosten' },
      { word: 'Peitsche', hint: 'Knallen' }, { word: 'Whirlpool', hint: 'Blubbern' }, { word: 'Massageöl', hint: 'Rücken' }, { word: 'Liebesbrief', hint: 'Parfümiert' }, { word: 'Playboy', hint: 'Häschen' },
      { word: 'Aktfoto', hint: 'Malkurs' }, { word: 'Kamasutra', hint: 'Indien' }, { word: 'Junggesellinnenabschied', hint: 'Schleier' }, { word: 'Schäferstündchen', hint: 'Mittags' }, { word: 'Bikini', hint: 'Strand' },
      { word: 'Push-up', hint: 'Ausschnitt' }, { word: 'Rendezvous', hint: 'Kerzenlicht' }, { word: 'Seitensprung', hint: 'Ertappt' }, { word: 'Wackelpo', hint: 'Twerken' }, { word: 'Strapse', hint: 'Oberschenkel' },
      { word: 'Korsett', hint: 'Schnüren' }, { word: 'Flitterwochen', hint: 'Suite' }, { word: 'Bettgeflüster', hint: 'Kopfkissen' }, { word: 'Aphrodisiakum', hint: 'Austern' }, { word: 'Striptease', hint: 'Langsam' },
      { word: 'Nacktbaden', hint: 'Mondschein' }, { word: 'FKK', hint: 'Ostsee' }, { word: 'Anbaggern', hint: 'Spruch' }, { word: 'Erotikroman', hint: 'Nachttisch' }, { word: 'Silikon', hint: 'Operation' },
      { word: 'Leidenschaft', hint: 'Flammen' }, { word: 'Liebesnest', hint: 'Versteck' }, { word: 'Rosenblätter', hint: 'Badewanne' }, { word: 'Candle-Light-Dinner', hint: 'Zweisamkeit' }, { word: 'Herzklopfen', hint: 'Aufregung' }
    ],
  },
  {
    id: 'music',
    name: 'Musik',
    icon: '🎵',
    hint: 'Musik',
    words: [
      { word: 'Gitarre', hint: 'Lagerfeuer' }, { word: 'Klavier', hint: 'Tasten' }, { word: 'Schlagzeug', hint: 'Sticks' }, { word: 'Geige', hint: 'Bogen' }, { word: 'Trompete', hint: 'Blech' },
      { word: 'Flöte', hint: 'Grundschule' }, { word: 'Saxofon', hint: 'Messing' }, { word: 'Cello', hint: 'Saiten' }, { word: 'Harfe', hint: 'Engel' }, { word: 'Mikrofon', hint: 'Gesang' },
      { word: 'Notenblatt', hint: 'Ständer' }, { word: 'Plattenspieler', hint: 'Vinyl' }, { word: 'Konzert', hint: 'Zugabe' }, { word: 'Oper', hint: 'Arien' }, { word: 'Band', hint: 'Proberaum' },
      { word: 'Chor', hint: 'Stimmen' }, { word: 'Orchester', hint: 'Graben' }, { word: 'Rap', hint: 'Reime' }, { word: 'Rock', hint: 'Lederjacke' }, { word: 'Pop', hint: 'Charts' },
      { word: 'Techno', hint: 'Rave' }, { word: 'Jazz', hint: 'Improvisation' }, { word: 'Klassik', hint: 'Beethoven' }, { word: 'Reggae', hint: 'Jamaika' }, { word: 'Metal', hint: 'Headbangen' },
      { word: 'Schlager', hint: 'Ballermann' }, { word: 'Ohrwurm', hint: 'Radio' }, { word: 'Playlist', hint: 'Shuffle' }, { word: 'Album', hint: 'Cover' }, { word: 'Single', hint: 'Neuerscheinung' },
      { word: 'Refrain', hint: 'Wiederholung' }, { word: 'Beat', hint: 'Kopfnicken' }, { word: 'Dirigent', hint: 'Taktstock' }, { word: 'Akkord', hint: 'Griffe' }, { word: 'Bass', hint: 'Wummern' },
      { word: 'Ukulele', hint: 'Hawaii' }, { word: 'Dudelsack', hint: 'Schottland' }, { word: 'Akkordeon', hint: 'Quetschen' }, { word: 'Triangel', hint: 'Dreieck' }, { word: 'Xylophon', hint: 'Stäbe' },
      { word: 'Panflöte', hint: 'Anden' }, { word: 'Mundharmonika', hint: 'Hosentasche' }, { word: 'Sänger', hint: 'Stimmbänder' }, { word: 'Hymne', hint: 'Stadion' }, { word: 'Wiegenlied', hint: 'Einschlafen' },
      { word: 'Weihnachtslied', hint: 'Dezember' }, { word: 'Konzertkarte', hint: 'Ausverkauft' }, { word: 'Boygroup', hint: 'Neunziger' }, { word: 'Autotune', hint: 'Roboterstimme' }, { word: 'Musical', hint: 'Broadway' },
      { word: 'Jodeln', hint: 'Alpen' }, { word: 'Straßenmusiker', hint: 'Hut' }
    ],
  },
  {
    id: 'crazy',
    name: 'Verrückt',
    icon: '🤪',
    hint: 'Verrückt',
    words: [
      { word: 'Backpfeifengesicht', hint: 'Ohrfeige' }, { word: 'Kummerspeck', hint: 'Trennung' }, { word: 'Treppenwitz', hint: 'Einfall' }, { word: 'Schnapsidee', hint: 'Betrunken' }, { word: 'Kuddelmuddel', hint: 'Durcheinander' },
      { word: 'Firlefanz', hint: 'Überflüssig' }, { word: 'Schabernack', hint: 'Streich' }, { word: 'Tohuwabohu', hint: 'Bibel' }, { word: 'Hokuspokus', hint: 'Abrakadabra' }, { word: 'Schlawiner', hint: 'Gauner' },
      { word: 'Dreikäsehoch', hint: 'Kind' }, { word: 'Hüftgold', hint: 'Röllchen' }, { word: 'Zappelphilipp', hint: 'Unruhig' }, { word: 'Erbsenzähler', hint: 'Kleinlich' }, { word: 'Schluckspecht', hint: 'Trinker' },
      { word: 'Naseweis', hint: 'Vorlaut' }, { word: 'Sitzfleisch', hint: 'Ausdauer' }, { word: 'Pantoffelheld', hint: 'Ehemann' }, { word: 'Sauklaue', hint: 'Handschrift' }, { word: 'Muskelkater', hint: 'Treppensteigen' },
      { word: 'Katzenjammer', hint: 'Reue' }, { word: 'Weltschmerz', hint: 'Melancholie' }, { word: 'Torschlusspanik', hint: 'Alter' }, { word: 'Verschlimmbessern', hint: 'Reparatur' }, { word: 'Gedankenkarussell', hint: 'Grübeln' },
      { word: 'Schweinehund', hint: 'Überwinden' }, { word: 'Sommerloch', hint: 'Nachrichten' }, { word: 'Schnappatmung', hint: 'Empörung' }, { word: 'Hexenschuss', hint: 'Bücken' }, { word: 'Quatschkopf', hint: 'Blödsinn' },
      { word: 'Wirrwarr', hint: 'Fäden' }, { word: 'Kladderadatsch', hint: 'Zusammenbruch' }, { word: 'Kabelsalat', hint: 'Schreibtisch' }, { word: 'Zungenbrecher', hint: 'Aussprache' }, { word: 'Luftschloss', hint: 'Träumerei' },
      { word: 'Drahtesel', hint: 'Zweirad' }, { word: 'Extrawurst', hint: 'Sonderwunsch' }, { word: 'Donnerbalken', hint: 'Plumpsklo' }, { word: 'Schnickschnack', hint: 'Deko' }, { word: 'Larifari', hint: 'Halbherzig' },
      { word: 'Mumpitz', hint: 'Erfunden' }, { word: 'Fisimatenten', hint: 'Ausflüchte' }, { word: 'Zinnober', hint: 'Theater' }, { word: 'Sperenzchen', hint: 'Zicken' }, { word: 'Suppenkasper', hint: 'Struwwelpeter' },
      { word: 'Nervensäge', hint: 'Geschwister' }, { word: 'Angsthase', hint: 'Mutprobe' }, { word: 'Purzelbaum', hint: 'Wiese' }, { word: 'Krawallschachtel', hint: 'Randale' }, { word: 'Trantüte', hint: 'Trödeln' }
    ],
  },
];
